// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * `gerbview/dialogs/dialog_map_gerber_layers_to_pcb.cpp` + `.h`:
 * `DIALOG_MAP_GERBER_LAYERS_TO_PCB`, the "Layer Selection" dialog Export to
 * PCB Editor opens (`gerbview_control.cpp` ExportToPcbnew).
 *
 * {@link DIALOG_MAP_GERBER_LAYERS_TO_PCB} is the controls' state, as the
 * wxFormBuilder members name it, with every handler the `.cpp` has, so the
 * dialog runs without a DOM; `dialog_map_gerber_layers_to_pcb_ui.tsx` draws it.
 *
 * Before the dialog shows, `findKnownGerbersLoaded` (`:447-464`) tries three
 * exact-match tables in order and offers the result as an automatic
 * assignment. The three tables are [data] in the CLAUDE.md sense: values KiCad
 * hardcodes, transcribed from its source rather than invented. The
 * inner-copper runs are generated by a loop, which is the same table —
 * `In1_Cu … In30_Cu` and `L2 … L30` and `G1 … G30` are consecutive in all
 * three, and upstream only spells them out because C++ has no better way to
 * write a map literal.
 */

import {
  GERBER_DRAWLAYERS_COUNT,
  IsValidLayer,
  type PCB_LAYER_ID,
  ToLAYER_ID,
} from '@ziroeda/common/layer_id.js';
import { LSET } from '@ziroeda/common/lset.js';
import { EXCELLON_IMAGE } from '../excellon_read_drill_file.js';
import type { GERBER_FILE_IMAGE } from '../gerber_file_image.js';
import type { GERBVIEW_FRAME } from '../gerbview_frame.js';
import {
  B_Adhes,
  B_Cu,
  B_CrtYd,
  B_Fab,
  B_Mask,
  B_Paste,
  B_SilkS,
  Cmts_User,
  CopperLayerToOrdinal,
  Dwgs_User,
  Eco1_User,
  Eco2_User,
  Edge_Cuts,
  F_Adhes,
  F_Cu,
  F_CrtYd,
  F_Fab,
  F_Mask,
  F_Paste,
  F_SilkS,
  In_Cu,
  IsCopperLayer,
  IsInnerCopperLayer,
  Margin,
  UNDEFINED_LAYER,
  UNSELECTED_LAYER,
} from '@ziroeda/common/layer_ids.js';

/**
 * `findNumX2GerbersLoaded`'s `kicadLayers` map
 * (`dialog_map_gerber_layers_to_pcb.cpp:711-758`), keyed exactly as upstream
 * keys it: on `GetBrdLayerSide()` for a copper file (falling back to
 * `GetBrdLayerId()` when the side reads `Inr`), and on `GetBrdLayerId()` and
 * `GetFileType()` concatenated for everything else — `"TopSoldermask"`,
 * `"BotPaste"`, `"PProfile"`.
 *
 * 45 entries: Top, L2…L30, Bot (31 copper) and 14 non-copper.
 */
export const X2_FILE_FUNCTION_LAYERS: ReadonlyMap<string, number> = new Map<string, number>([
  ['Top', F_Cu],
  // `{ wxT( "L2" ), In1_Cu } … { wxT( "L30" ), In29_Cu }` — L(n+1) is In(n).Cu,
  // because L1 is always the top copper layer.
  ...Array.from({ length: 29 }, (_, i): [string, number] => [`L${i + 2}`, In_Cu(i + 1)]),
  ['Bot', B_Cu],
  ['BotGlue', B_Adhes],
  ['TopGlue', F_Adhes],
  ['BotPaste', B_Paste],
  ['TopPaste', F_Paste],
  ['BotLegend', B_SilkS],
  ['TopLegend', F_SilkS],
  ['BotSoldermask', B_Mask],
  ['TopSoldermask', F_Mask],
  ['FabricationDrawing', Dwgs_User],
  ['OtherDrawing', Cmts_User],
  ['TopAssemblyDrawing', F_Fab],
  ['BotAssemblyDrawing', B_Fab],
  ['PProfile', Edge_Cuts], // Plated PCB outline
  ['NPProfile', Edge_Cuts], // Non-plated PCB outline
]);

/**
 * `findNumKiCadGerbersLoaded`'s `kicadLayers` map
 * (`dialog_map_gerber_layers_to_pcb.cpp:580-636`) — the suffix KiCad's plotter
 * appends to the project name, `-` included.
 *
 * 54 entries. Note the four aliases upstream carries for the layers whose
 * plotted name was lengthened (`-B_Adhesive` beside `-B_Adhes`,
 * `-F_Silkscreen` beside `-F_SilkS`) and that `-F_Courtyard` / `-B_Courtyard`
 * are spelled out while the layer id is `F_CrtYd` / `B_CrtYd`.
 */
export const KICAD_SUFFIX_LAYERS: ReadonlyMap<string, number> = new Map<string, number>([
  ['-F_Cu', F_Cu],
  ...Array.from({ length: 30 }, (_, i): [string, number] => [`-In${i + 1}_Cu`, In_Cu(i + 1)]),
  ['-B_Cu', B_Cu],
  ['-B_Adhes', B_Adhes],
  ['-F_Adhes', F_Adhes],
  ['-B_Adhesive', B_Adhes],
  ['-F_Adhesive', F_Adhes],
  ['-B_Paste', B_Paste],
  ['-F_Paste', F_Paste],
  ['-B_SilkS', B_SilkS],
  ['-F_SilkS', F_SilkS],
  ['-B_Silkscreen', B_SilkS],
  ['-F_Silkscreen', F_SilkS],
  ['-B_Mask', B_Mask],
  ['-F_Mask', F_Mask],
  ['-F_Fab', F_Fab],
  ['-B_Fab', B_Fab],
  ['-Dwgs_User', Dwgs_User],
  ['-Cmts_User', Cmts_User],
  ['-Eco1_User', Eco1_User],
  ['-Eco2_User', Eco2_User],
  ['-Edge_Cuts', Edge_Cuts],
  ['-Margin', Margin],
  ['-F_Courtyard', F_CrtYd],
  ['-B_Courtyard', B_CrtYd],
]);

/**
 * `findNumAltiumGerbersLoaded`'s `altiumExt` map
 * (`dialog_map_gerber_layers_to_pcb.cpp:473-515`) — the uppercased file
 * extension, no dot.
 *
 * 41 entries. `GM1`/`GM2` are Altium mechanical layers 1 and 2 and go to
 * `Eco1_User`/`Eco2_User`; `GKO` is the outline. There is no drill extension
 * in the table, which is one of the three reasons a `.drl` file reaches
 * `ExportPcb` unmapped.
 */
export const ALTIUM_EXTENSION_LAYERS: ReadonlyMap<string, number> = new Map<string, number>([
  ['GTL', F_Cu], // Top copper
  // "Inner layers 1 - 30"
  ...Array.from({ length: 30 }, (_, i): [string, number] => [`G${i + 1}`, In_Cu(i + 1)]),
  ['GBL', B_Cu], // Bottom copper
  ['GTP', F_Paste], // Paste top
  ['GBP', B_Paste], // Paste bottom
  ['GTO', F_SilkS], // Silkscreen top
  ['GBO', B_SilkS], // Silkscreen bottom
  ['GTS', F_Mask], // Soldermask top
  ['GBS', B_Mask], // Soldermask bottom
  ['GM1', Eco1_User], // Altium mechanical layer 1
  ['GM2', Eco2_User], // Altium mechanical layer 2
  ['GKO', Edge_Cuts], // PCB Outline
]);

/**
 * `wxFileName::GetName()` — the file name with the path and the extension
 * removed. Upstream builds a `wxFileName` from `m_FileName` before reading
 * either half (`:543`, `:664`).
 */
function fileNameBase(path: string): string {
  const base = stripDirs(path);
  const dot = base.lastIndexOf('.');
  return dot <= 0 ? base : base.slice(0, dot);
}

/** `wxFileName::GetExt()` — the text after the last dot, or the empty string. */
function fileNameExt(path: string): string {
  const base = stripDirs(path);
  const dot = base.lastIndexOf('.');
  return dot <= 0 ? '' : base.slice(dot + 1);
}

/**
 * The file name without any directory part. Both separators, because a name
 * that reached us through a browser upload can carry either.
 *
 * A leading dot is not an extension: `wxFileName` treats `.profile` as a name,
 * which is why both helpers above test `dot <= 0` rather than `dot < 0`.
 */
function stripDirs(path: string): string {
  return path.slice(Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\')) + 1);
}

/**
 * `findNumX2GerbersLoaded` (`:705-832`), for one image.
 *
 * Guarded by `m_IsX2_file`, which upstream sets only once a `%TF` file
 * function has parsed (`gerbview/rs274x.cpp:395-397`) — our
 * `fileFunction !== null`, the same test `isX2File` already makes in
 * `gerberAuxControls.ts:318`. An Excellon image carries a *synthesised*
 * function (`Other,Drill`) but is not an X2 file upstream, so it is excluded
 * here; the point is moot in that `"Other" + "Drill"` matches no entry either
 * way, but the guard should say what upstream's says.
 */
function findX2Layer(image: GERBER_FILE_IMAGE): number {
  if (image instanceof EXCELLON_IMAGE) return UNSELECTED_LAYER;
  const f = image.m_FileFunction;
  if (!image.m_IsX2_file || f === null) return UNSELECTED_LAYER;
  let mapThis: string;

  if (f.IsCopper()) {
    // "Returns Top, Bot or Inr" — and an inner layer needs its number, so the
    // key falls back to the layer id ("L2", "L5", …).
    mapThis = f.GetBrdLayerSide().toLowerCase() === 'inr' ? f.GetBrdLayerId() : f.GetBrdLayerSide();
  } else {
    mapThis = f.GetBrdLayerId() + f.GetFileType();
  }

  return X2_FILE_FUNCTION_LAYERS.get(mapThis) ?? UNSELECTED_LAYER;
}

/**
 * `findNumKiCadGerbersLoaded` (`:574-702`), for one image.
 *
 * "KiCad appends a suffix consisting of a '-' and the name of the layer to the
 * project name. We need to isolate the suffix": the search is for the LAST
 * `-` in the name, and the suffix keeps the dash.
 */
function findKiCadSuffixLayer(image: GERBER_FILE_IMAGE): number {
  const layerName = fileNameBase(image.m_FileName);
  const dashPos = layerName.lastIndexOf('-');
  if (dashPos === -1) return UNSELECTED_LAYER;
  return KICAD_SUFFIX_LAYERS.get(layerName.slice(dashPos)) ?? UNSELECTED_LAYER;
}

/** `findNumAltiumGerbersLoaded` (`:467-571`), for one image. */
function findAltiumExtensionLayer(image: GERBER_FILE_IMAGE): number {
  return (
    ALTIUM_EXTENSION_LAYERS.get(fileNameExt(image.m_FileName).toUpperCase()) ?? UNSELECTED_LAYER
  );
}

/**
 * `findKnownGerbersLoaded` (`:447-464`): the three tables in order, first
 * claim wins.
 *
 * Upstream's ordering is not incidental. Each finder skips a row that is
 * already something other than `UNSELECTED_LAYER` ("This will preserve them"),
 * so an X2 attribute beats a KiCad file name, which beats an Altium extension.
 * A KiCad-plotted X2 gerber matches the first two and must take the first.
 */
export function findKnownGerberLayer(image: GERBER_FILE_IMAGE): number {
  const x2 = findX2Layer(image);
  if (x2 !== UNSELECTED_LAYER) return x2;

  const kicad = findKiCadSuffixLayer(image);
  if (kicad !== UNSELECTED_LAYER) return kicad;

  return findAltiumExtensionLayer(image);
}

// ---------------------------------------------------------------------------
// The dialog

/** `m_comboCopperLayersCount`'s sixteen entries (`_base.cpp:66-82`). [data] */
export const COPPER_LAYERS_COUNT_CHOICES: readonly string[] = Array.from(
  { length: 16 },
  (_, i) => `${(i + 1) * 2} Layers`,
);

/** `_( "Do not export" )`, the label of an `UNSELECTED_LAYER` row. [data] */
export const DO_NOT_EXPORT = 'Do not export';
/** `_( "Hole data" )`, the label of an `UNDEFINED_LAYER` row. [data] */
export const HOLE_DATA = 'Hole data';

/**
 * The two foreground colours a mapped-layer wxStaticText takes: `*wxBLUE` for a
 * row that is not exported, `wxColour( 255, 0, 128 )` ("fuchsia") for one that
 * is. The colours themselves are in shell.css.
 */
export type MAPPED_LAYER_COLOUR = 'blue' | 'fuchsia';

/** One `m_layersList[ii]` wxStaticText: its label and its foreground colour. */
export interface MAPPED_LAYER_TEXT {
  label: string;
  colour: MAPPED_LAYER_COLOUR;
}

/**
 * The labels `initDialog` sizes the mapped-layer text to fit (`:182-194`): the
 * default "Do not export" and `LSET::Name` of every one of the
 * GERBER_DRAWLAYERS_COUNT layer ids, the widest of which is the `SetMinSize`
 * every row gets so no later choice truncates.
 */
export function mappedLayerSizingLabels(): string[] {
  const labels = [DO_NOT_EXPORT];

  for (let jj = 0; jj < GERBER_DRAWLAYERS_COUNT; ++jj) labels.push(LSET.Name(jj as PCB_LAYER_ID));

  return labels;
}

/** The label and colour a row takes for `aLayer` (`:333-347`, `:383-406`). */
function mappedLayerText(aLayer: number): MAPPED_LAYER_TEXT {
  if (aLayer === UNSELECTED_LAYER) return { label: DO_NOT_EXPORT, colour: 'blue' };

  if (aLayer === UNDEFINED_LAYER) return { label: HOLE_DATA, colour: 'fuchsia' };

  return { label: LSET.Name(aLayer as PCB_LAYER_ID), colour: 'fuchsia' };
}

/**
 * `DIALOG_MAP_GERBER_LAYERS_TO_PCB` (`dialog_map_gerber_layers_to_pcb.cpp`):
 * one row per loaded Gerber — "Layer N:", its file name, a "..." button and
 * the board layer it goes to — the copper layer count, and Store Choice / Get
 * Stored Choice / Reset.
 *
 * **`initDialog` is a separate async call.** Upstream's constructor runs it
 * (`:59-69`), and it can raise a modal "Automatic Layer Assignment" question
 * in the middle; a browser has no nested event loop, so the question is a
 * promise and the caller awaits `initDialog()` before `ShowModal`.
 */
export class DIALOG_MAP_GERBER_LAYERS_TO_PCB {
  /**
   * `static int m_exportBoardCopperLayersCount = 2` (`:48`): a class static, so
   * the count chosen last time is what the next dialog opens on, for the rest
   * of the run.
   */
  static m_exportBoardCopperLayersCount = 2;

  private readonly m_Parent: GERBVIEW_FRAME;

  /** Number of initialized Gerber layers. */
  m_gerberActiveLayersCount = 0;

  /** Indexes Gerber layers to PCB file layers. */
  m_layersLookUpTable: number[] = new Array<number>(GERBER_DRAWLAYERS_COUNT).fill(UNSELECTED_LAYER);
  m_buttonTable: number[] = new Array<number>(GERBER_DRAWLAYERS_COUNT + 1).fill(-1);

  /** The two static texts before each row's button: "Layer %d:" and the file name. */
  m_layerLabels: { layer: string; fileName: string }[] = [];
  /** `m_layersList[ii]`, the static text after each row's button. */
  m_layersList: MAPPED_LAYER_TEXT[] = [];

  /** `m_comboCopperLayersCount->GetSelection()`. */
  m_comboCopperLayersCount = 0;
  /** `m_buttonRetrieve->IsEnabled()`. */
  m_buttonRetrieveEnabled = true;
  /** `m_staticlineSep->IsShown()`. */
  m_staticlineSepShown = true;

  constructor(aParent: GERBVIEW_FRAME) {
    this.m_Parent = aParent;
  }

  /** `GetLayersLookUpTable()`. */
  GetLayersLookUpTable(): number[] {
    return this.m_layersLookUpTable;
  }

  /** `static GetCopperLayersCount()`. */
  static GetCopperLayersCount(): number {
    return DIALOG_MAP_GERBER_LAYERS_TO_PCB.m_exportBoardCopperLayersCount;
  }

  private get count(): number {
    return DIALOG_MAP_GERBER_LAYERS_TO_PCB.m_exportBoardCopperLayersCount;
  }

  private set count(aCount: number) {
    DIALOG_MAP_GERBER_LAYERS_TO_PCB.m_exportBoardCopperLayersCount = aCount;
  }

  /** `initDialog()` (`:72-254`). */
  async initDialog(): Promise<void> {
    // `static_cast<GERBVIEW_SETTINGS*>( Kiface().KifaceSettings() )`
    const config = this.m_Parent.gvconfig();

    for (let ii = 0; ii < GERBER_DRAWLAYERS_COUNT; ++ii) {
      // Specify the default value for each member of these arrays.
      this.m_buttonTable[ii] = -1;
      this.m_layersLookUpTable[ii] = UNSELECTED_LAYER;
    }

    // Ensure we have:
    //    At least 2 copper layers and less than max pcb copper layers count
    //    Even number of layers because a board *must* have even layers count
    this.normalizeBrdLayersCount();

    this.m_comboCopperLayersCount = Math.trunc(this.count / 2) - 1;

    this.m_gerberActiveLayersCount = 0;
    const images = this.m_Parent.GetGerberLayout().GetImagesList();

    for (let ii = 0; ii < GERBER_DRAWLAYERS_COUNT; ++ii) {
      if (images.GetGbrImage(ii) === null) break;

      this.m_buttonTable[this.m_gerberActiveLayersCount] = ii;
      this.m_gerberActiveLayersCount++;
    }

    // Only one list is enough
    if (this.m_gerberActiveLayersCount <= GERBER_DRAWLAYERS_COUNT / 2)
      this.m_staticlineSepShown = false;

    this.m_layerLabels = [];
    this.m_layersList = [];

    for (let ii = 0; ii < this.m_gerberActiveLayersCount; ii++) {
      this.m_layerLabels.push({
        layer: `Layer ${this.m_buttonTable[ii]! + 1}:`,
        // Add file name and extension without path.
        fileName: stripDirs(images.GetGbrImage(ii)!.m_FileName),
      });

      // All layers default to "Do Not Export" displayed in blue
      this.m_layersList.push(mappedLayerText(UNSELECTED_LAYER));
    }

    // If the user has never stored any Gerber to KiCad layer mapping,
    // then disable the button to retrieve it
    if (config.m_GerberToPcbLayerMapping.length === 0) this.m_buttonRetrieveEnabled = false;

    const gerber2KicadMapping: number[] = [];

    // See how many of the loaded Gerbers can be mapped to KiCad layers automatically
    const numMappedGerbers = this.findKnownGerbersLoaded(gerber2KicadMapping);

    if (numMappedGerbers > 0) {
      // KICAD_MESSAGE_DIALOG( …, wxOK | wxCANCEL | wxOK_DEFAULT )
      const ok = await this.m_Parent
        .Host()
        .OkCancelMessageDialog(
          `Gerbers with known layers: ${numMappedGerbers}\n\nAssign to matching PCB layers?`,
          'Automatic Layer Assignment',
        );

      if (ok) {
        let total_copper = 0;

        for (let ii = 0; ii < this.m_gerberActiveLayersCount; ii++) {
          const currLayer = gerber2KicadMapping[ii]!;

          if (IsCopperLayer(currLayer)) total_copper++;

          // Default to "Do Not Export" for unselected or undefined layer. Note
          // that UNDEFINED_LAYER here reads as a layer name, not "Hole data"
          // (`:231-246`) — the tables never produce it.
          if (currLayer === UNSELECTED_LAYER) {
            this.m_layersList[ii] = mappedLayerText(UNSELECTED_LAYER);

            // Set the layer internally to unselected
            this.m_layersLookUpTable[ii] = UNSELECTED_LAYER;
          } else {
            this.m_layersList[ii] = {
              label: LSET.Name(currLayer as PCB_LAYER_ID),
              colour: 'fuchsia',
            };

            // Set the layer internally to the matching KiCad layer
            this.m_layersLookUpTable[ii] = currLayer;
          }
        }

        // Reset the number of copper layers to the total found. Not normalised:
        // three copper layers leave the count at 3 and the combo on "2 Layers"
        // until TransferDataFromWindow rounds it up.
        this.count = Math.max(total_copper, 2);
        this.m_comboCopperLayersCount = Math.trunc(this.count / 2) - 1;
      }
    }
  }

  /** `normalizeBrdLayersCount()` (`:257-268`). */
  private normalizeBrdLayersCount(): void {
    if (this.count & 1) this.count++;

    if (this.count > GERBER_DRAWLAYERS_COUNT) this.count = GERBER_DRAWLAYERS_COUNT;

    if (this.count < 2) this.count = 2;
  }

  /** `OnBrdLayersCountSelection` (`:271-275`): the combo's `GetSelection()`. */
  OnBrdLayersCountSelection(aSelection: number): void {
    this.m_comboCopperLayersCount = aSelection;
    this.count = (aSelection + 1) * 2;
  }

  /** `OnResetClick` (`:278-291`). */
  OnResetClick(): void {
    for (let ii = 0; ii < this.m_gerberActiveLayersCount; ++ii) {
      this.m_layersLookUpTable[ii] = UNSELECTED_LAYER;
      this.m_layersList[ii] = mappedLayerText(UNSELECTED_LAYER);
      this.m_buttonTable[ii] = ii;
    }
  }

  /** `OnStoreSetup` (`:294-307`). */
  OnStoreSetup(): void {
    const config = this.m_Parent.gvconfig();
    config.m_BoardLayersCount = this.count;

    config.m_GerberToPcbLayerMapping = [];

    for (let ii = 0; ii < GERBER_DRAWLAYERS_COUNT; ++ii)
      config.m_GerberToPcbLayerMapping.push(this.m_layersLookUpTable[ii]!);

    // Enable the "Get Stored Choice" button in case it was disabled in "initDialog()"
    // due to no previously stored choices.
    this.m_buttonRetrieveEnabled = true;
  }

  /** `OnGetSetup` (`:310-349`). */
  OnGetSetup(): void {
    const config = this.m_Parent.gvconfig();

    this.count = config.m_BoardLayersCount;
    this.normalizeBrdLayersCount();

    this.m_comboCopperLayersCount = Math.trunc(this.count / 2) - 1;

    for (let ii = 0; ii < GERBER_DRAWLAYERS_COUNT; ++ii) {
      // Ensure the layer mapping in config exists for this layer, and store it
      if (ii >= config.m_GerberToPcbLayerMapping.length) break;

      this.m_layersLookUpTable[ii] = config.m_GerberToPcbLayerMapping[ii]!;
    }

    for (let ii = 0; ii < this.m_gerberActiveLayersCount; ii++)
      this.m_layersList[ii] = mappedLayerText(this.m_layersLookUpTable[ii]!);
  }

  /**
   * `OnSelectLayer` (`:352-412`): row `ii`'s "..." button, which opens
   * `GERBVIEW_FRAME::SelectPCBLayer` on the row's current layer.
   */
  async OnSelectLayer(ii: number): Promise<void> {
    if (ii < 0 || ii >= GERBER_DRAWLAYERS_COUNT) {
      console.assert(false, 'Bad layer id');
      return;
    }

    let jj = this.m_layersLookUpTable[this.m_buttonTable[ii]!]!;

    // (Defaults to "Copper" layer.)
    if (jj !== UNSELECTED_LAYER && jj !== UNDEFINED_LAYER && !IsValidLayer(jj)) jj = B_Cu;

    // Get file name of Gerber loaded on this layer
    const fn = stripDirs(
      this.m_Parent.GetGerberLayout().GetImagesList().GetGbrImage(ii)!.m_FileName,
    );

    // Surround it with quotes to make it stand out on the dialog title bar
    const layerName = `"${fn}"`;

    // Display dialog to let user select a layer for the Gerber
    jj = await this.m_Parent.SelectPCBLayer(jj, this.count, layerName);

    if (jj !== UNSELECTED_LAYER && jj !== UNDEFINED_LAYER && !IsValidLayer(jj)) return;

    if (jj !== this.m_layersLookUpTable[this.m_buttonTable[ii]!]) {
      this.m_layersLookUpTable[this.m_buttonTable[ii]!] = jj;
      this.m_layersList[ii] = mappedLayerText(jj);
    }
  }

  /**
   * `TransferDataFromWindow` (`:415-444`): refuses OK — the dialog stays open —
   * when a chosen inner layer does not fit the copper count.
   */
  TransferDataFromWindow(): boolean {
    // Board must have enough copper layers to handle selected internal layers.
    this.normalizeBrdLayersCount();

    let inner_layer_max = 0;

    for (let ii = 0; ii < GERBER_DRAWLAYERS_COUNT; ++ii) {
      if (IsInnerCopperLayer(this.m_layersLookUpTable[ii]!)) {
        if (this.m_layersLookUpTable[ii]! > inner_layer_max)
          inner_layer_max = this.m_layersLookUpTable[ii]!;
      }
    }

    // inner_layer_max must be less than or equal to the number of internal copper layers
    // internal copper layers = m_exportBoardCopperLayersCount-2
    if (CopperLayerToOrdinal(ToLAYER_ID(inner_layer_max)) > this.count - 2) {
      void this.m_Parent
        .Host()
        .MessageBox(
          'Exported board does not have enough copper layers to handle selected inner layers',
        );
      return false;
    }

    return true;
  }

  /**
   * `findKnownGerbersLoaded` (`:447-464`) over the loaded rows: each row's
   * layer from the first of the three tables that claims it, and how many
   * were claimed. Upstream's three finders each skip a row an earlier one
   * claimed, which is {@link findKnownGerberLayer}'s first-claim-wins, so the
   * sum of their three counts is the number of claimed rows.
   */
  findKnownGerbersLoaded(aGerber2KicadMapping: number[]): number {
    const images = this.m_Parent.GetGerberLayout().GetImagesList();
    let numKnownGerbers = 0;

    aGerber2KicadMapping.length = 0;

    for (let ii = 0; ii < this.m_gerberActiveLayersCount; ii++) {
      const image = images.GetGbrImage(ii);
      const layer = image ? findKnownGerberLayer(image) : UNSELECTED_LAYER;

      aGerber2KicadMapping.push(layer);

      if (layer !== UNSELECTED_LAYER) numKnownGerbers++;
    }

    return numKnownGerbers;
  }
}
