// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * Plot to SVG (DIALOG_PLOT_SCHEMATIC, SVG format): the on-screen schematic
 * renderer's draws are handed, through a Canvas2D-shaped adapter, to the
 * common `SVG_PLOTTER` — the class `SCH_PLOTTER::plotOneSheetSVG` plots
 * through. Every expectation below is read off `kicad-cli sch export svg` of
 * this same sheet (10.0.5), not off our own output.
 */
import { describe, it, expect } from 'vitest';
import { parse } from '@ziroeda/sexpr';
import { readSchematic } from '@ziroeda/eeschema';
import { sheetToSvg } from '@ziroeda/designer/src/editors/schematic/render/plot.js';
import { KICAD_DEFAULT } from '@ziroeda/designer/src/editors/schematic/theme.js';

const SCH = `(kicad_sch (version 20231120) (generator "test") (paper "A4")
  (lib_symbols
    (symbol "Device:R" (pin_numbers hide) (pin_names (offset 0))
      (property "Reference" "R" (at 2.032 0 90))
      (property "Value" "R" (at 0 0 90))
      (symbol "R_0_1"
        (rectangle (start -1.016 -2.54) (end 1.016 2.54)
          (stroke (width 0.254) (type default)) (fill (type none))))
      (symbol "R_1_1"
        (pin passive line (at 0 3.81 270) (length 1.27) (name "~" (effects (font (size 1.27 1.27)))) (number "1" (effects (font (size 1.27 1.27)))))
        (pin passive line (at 0 -3.81 90) (length 1.27) (name "~" (effects (font (size 1.27 1.27)))) (number "2" (effects (font (size 1.27 1.27))))))))
  (wire (pts (xy 100 100) (xy 120 100)) (stroke (width 0) (type default)) (uuid "w-1"))
  (symbol (lib_id "Device:R") (at 100 90 0) (uuid "sym-1")
    (property "Reference" "R1" (at 102 88 0))
    (property "Value" "10k" (at 102 92 0))))`;

describe('plot to SVG', () => {
  it('renders a well-formed SVG at the page size with vector geometry', () => {
    const doc = readSchematic(parse(SCH));
    const svg = sheetToSvg(doc, KICAD_DEFAULT, {
      color: true,
      drawingSheet: true,
      background: false,
    });

    expect(svg.startsWith('<?xml version="1.0" standalone="no"?>\n')).toBe(true);
    expect(svg.endsWith('</g> \n</svg>\n')).toBe(true);
    // A4 landscape is 297.0022 x 210.0072 mm, NOT a clean 297 x 210, and the
    // viewBox is in the same millimetres. kicad-cli writes exactly this line:
    // `SVG_PLOTTER::StartPlot` sizes the page from PAGE_INFO's 11693 x 8268
    // mils (SVG_plotter.cpp:190, :798-800), 11693 x 0.0254 = 297.0022.
    expect(svg).toContain(
      '  width="297.0022mm" height="210.0072mm" viewBox="0.0000 0.0000 297.0022 210.0072">\n',
    );
    expect(svg).toContain('  <desc>Image generated by Eeschema-SVG </desc>\n');
    // Wire + symbol body + drawing-sheet border all emit paths.
    expect((svg.match(/<path/g) ?? []).length).toBeGreaterThan(3);
    // The wire, as kicad-cli plots it: MoveTo/FinishTo in mm, in the wire colour.
    expect(svg).toContain('stroke:#009600; stroke-width:0.1524;');
    expect(svg).toContain('<path d="M100.0000 100.0000\nL120.0000 100.0000\n" />');
  });

  it('black-and-white output uses only black strokes', () => {
    const doc = readSchematic(parse(SCH));
    const svg = sheetToSvg(doc, KICAD_DEFAULT, {
      color: false,
      drawingSheet: false,
      background: false,
    });
    const strokes = new Set(svg.match(/stroke:#[0-9A-F]{6}/g));
    // kicad-cli --black-and-white: every stroke of this sheet is #000000.
    expect([...strokes]).toEqual(['stroke:#000000']);
  });

  it('honours a portrait custom-oriented page size', () => {
    const doc = readSchematic(parse(SCH.replace('(paper "A4")', '(paper "A3" portrait)')));
    const svg = sheetToSvg(doc, KICAD_DEFAULT, {
      color: true,
      drawingSheet: false,
      background: false,
    });
    // A3 portrait swaps the landscape pair: 16535 x 11693 mils becomes
    // 11693 x 16535, i.e. 297.0022 x 419.989 mm — kicad-cli's line verbatim.
    expect(svg).toContain(
      '  width="297.0022mm" height="419.9890mm" viewBox="0.0000 0.0000 297.0022 419.9890">\n',
    );
  });
});
