#!/usr/bin/env python3
"""
Extract every TOOL_ACTION from KiCad's `*_actions.cpp` into the catalogue
`designer/src/ui/action_catalogue.ts`.

`PANEL_TOOLBAR_CUSTOMIZATION::populateActions` lists `m_availableTools` — every
registered action — filtered only by `isActionSupported`, which is a NAME PREFIX
test (`panel_toolbar_customization.cpp:207-245`), and by
`TOOLBAR_STATE::HIDDEN`. So the right-hand list is the whole catalogue for the
frame's app, including actions that frame cannot run: KiCad's Symbol Editor page
offers "Add Column After" and "Align to Bottom" just the same.

Transcribing 800 actions by hand would be error-prone in a way this is not, and
the fields are mechanical: `.Name()`, `.FriendlyName()`, `.Tooltip()`,
`.Icon( BITMAPS::… )`, `.ToolbarState( TOOLBAR_STATE::HIDDEN )`.

Run with the reference checkout present:

    python3 tools/kicad/extract_actions.py > designer/src/ui/action_catalogue.ts
    npx biome check --write designer/src/ui/action_catalogue.ts

The second step is not optional: this prints JSON, which is valid TypeScript but
not the style biome enforces, so the committed file is the formatted one and a
regeneration without it shows a whole-file diff.

It is committed as GENERATED DATA, with the generator beside it, because the
reference tree is not in this repo and CI cannot regenerate it.
"""
import json
import pathlib
import re
import sys

REF = pathlib.Path('/home/akshay/kicad-reference')
SOURCES = [
    ('common', 'common/tool/actions.cpp'),
    ('eeschema', 'eeschema/tools/sch_actions.cpp'),
    ('pcbnew', 'pcbnew/tools/pcb_actions.cpp'),
    ('gerbview', 'gerbview/tools/gerbview_actions.cpp'),
    ('plEditor', 'pagelayout_editor/tools/pl_actions.cpp'),
]


def unquote(text: str) -> str:
    """`_( "a" "b" )` — wxWidgets splits long strings across adjacent literals."""
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"', text)
    return ''.join(parts).replace('\\"', '"').replace('\\n', '\n')


def extract() -> list[dict]:
    out: dict[str, dict] = {}
    for _app, rel in SOURCES:
        path = REF / rel
        if not path.exists():
            print(f'missing: {path}', file=sys.stderr)
            continue
        text = path.read_text()
        # Each declaration starts at column 0; the body runs to the blank line.
        for chunk in re.split(r'\nTOOL_ACTION\s+', text)[1:]:
            body = chunk.split('\n\n', 1)[0]
            name = re.search(r'\.Name\(\s*"([^"]+)"\s*\)', body)
            friendly = re.search(r'\.FriendlyName\(\s*_\(([^)]*)\)\s*\)', body, flags=re.S)
            if not name or not friendly:
                continue
            tip = re.search(r'\.Tooltip\(\s*_\(([^)]*)\)\s*\)', body, flags=re.S)
            icon = re.search(r'\.Icon\(\s*BITMAPS::(\w+)\s*\)', body)
            rec = {
                'name': name.group(1),
                'label': unquote(friendly.group(1)),
            }
            if tip:
                rec['tip'] = unquote(tip.group(1))
            if icon:
                rec['icon'] = icon.group(1)
            if 'TOOLBAR_STATE::HIDDEN' in body:
                rec['hidden'] = True
            # Keyed by the full action name, which is unique and is what
            # `TOOLBAR_ITEM::m_ActionName` stores (`toolbar_configuration.cpp:54`).
            out[rec['name']] = rec
    return sorted(out.values(), key=lambda r: r['name'])


def main() -> None:
    records = extract()
    ts = json.dumps(records, indent=2, ensure_ascii=False)
    # JSON keys are quoted; TypeScript is happy with that and it keeps the diff
    # mechanical rather than hand-formatted.
    print('// SPDX-License-Identifier: GPL-3.0-or-later')
    print('// Copyright (C) 2026 ZiroEDA and contributors.')
    print('// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.')
    print('//')
    print('// GENERATED by tools/kicad/extract_actions.py from the pinned KiCad')
    print('// reference. Do not edit by hand: re-run the generator.')
    print('')
    print('/** One `TOOL_ACTION`, as `PANEL_TOOLBAR_CUSTOMIZATION` needs it. */')
    print('export interface CatalogueAction {')
    print('  /** `.Name()` — `TOOLBAR_ITEM::m_ActionName`, and unique. */')
    print('  readonly name: string;')
    print('  /** `.FriendlyName()` — `GetFriendlyName()`, the row label. */')
    print('  readonly label: string;')
    print('  /** `.Tooltip()` — `entry.tooltip`, which the search text includes. */')
    print('  readonly tip?: string;')
    print('  /** `.Icon( BITMAPS::… )`, absent for an action with none. */')
    print('  readonly icon?: string;')
    print('  /** `.ToolbarState( TOOLBAR_STATE::HIDDEN )` — never offered. */')
    print('  readonly hidden?: boolean;')
    print('}')
    print('')
    print(f'/** Every action KiCad registers: {len(records)} of them. */')
    print('export const ACTION_CATALOGUE: readonly CatalogueAction[] =', ts, 'as const;')


if __name__ == '__main__':
    main()
