#!/usr/bin/env python3
"""
Translate KiCad's `eeschema/tools/sch_actions.cpp` into `eeschema/tools/sch_actions.ts`: every
`TOOL_ACTION SCH_ACTIONS::x( TOOL_ACTION_ARGS() ... );` as a static TOOL_ACTION of the TS class,
in the C++ order, the builder calls spelled as pcbnew/tools/pcb_actions.ts spells them.

The builder calls are mechanical (`.Name`, `.Scope`, `.DefaultHotkey`, `.FriendlyName`, `.Icon`,
`.Flags`, `.ToolbarState`, `.Parameter`, ...), which is why this is generated rather than typed:

    python3 tools/kicad/port_sch_actions.py > eeschema/tools/sch_actions.ts
    npx biome check --write eeschema/tools/sch_actions.ts

Committed as GENERATED CODE with the generator beside it; the reference tree is not in the repo.
"""
import pathlib
import re
import sys

REF = pathlib.Path('/home/akshay/kicad-reference/eeschema/tools/sch_actions.cpp')

HEADER = '''// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * `SCH_ACTIONS` (eeschema/tools/sch_actions.h, sch_actions.cpp): every tool action of the
 * schematic and symbol editors, each a static TOOL_ACTION registered with ACTION_MANAGER as it is
 * built, exactly as the C++ statics are. The strings are the C++'s untranslated `_()` sources.
 * GENERATED by tools/kicad/port_sch_actions.py from sch_actions.cpp (KiCad 10.0.6); edit the
 * generator, not this file.
 */
import { WXK } from '@ziroeda/core/wx_keycodes.js';
import { KICAD_T } from '@ziroeda/core/typeinfo.js';
import { BITMAPS } from '@ziroeda/common/bitmaps/bitmaps_list.js';
import { SHAPE_T } from '@ziroeda/common/eda_shape.js';
import { SCH_LAYER_ID } from '@ziroeda/common/layer_id.js';
import { ACTIONS } from '@ziroeda/common/tool/actions.js';
import {
  TOOL_ACTION,
  TOOL_ACTION_ARGS,
  TOOL_ACTION_FLAGS,
  TOOL_ACTION_SCOPE,
  TOOLBAR_STATE,
} from '@ziroeda/common/tool/tool_action.js';
import { MD_ALT, MD_CTRL, MD_SHIFT } from '@ziroeda/common/tool/tool_event.js';
import type { SCH_BITMAP } from '../sch_bitmap.js';
import type { SCH_LINE } from '../sch_line.js';
import type { SCH_SYMBOL } from '../sch_symbol.js';

/** `'N'` in a hotkey: the character's code, as C++ `int` promotion gives it. */
const ch = (c: string): number => c.charCodeAt(0);

/** `LINE_MODE` (eeschema_settings.h:45). */
export enum LINE_MODE {
  LINE_MODE_FREE = 0,
  LINE_MODE_90 = 1,
  LINE_MODE_45 = 2,

  LINE_MODE_COUNT,
}

/** `DRAW_SEGMENT_EVENT_PARAMS` (tools/sch_line_wire_bus_tool.h:62). */
export interface DRAW_SEGMENT_EVENT_PARAMS {
  layer: SCH_LAYER_ID;
  quitOnDraw: boolean;
  sourceSegment: SCH_LINE | null;
}

/** `DESIGN_BLOCK` (common/design_block.h): pending with the design-block library. */
export type DESIGN_BLOCK = unknown;

/** `SCH_ACTIONS::PLACE_SYMBOL_PARAMS` (sch_actions.h:330). */
export interface PLACE_SYMBOL_PARAMS {
  ///< Provide a symbol to place
  m_Symbol: SCH_SYMBOL | null;
  ///< If a symbol is provide, reannotate it?
  m_Reannotate: boolean;
}

/** `SCH_ACTIONS::PLACE_SYMBOL_UNIT_PARAMS` (sch_actions.h:338). */
export interface PLACE_SYMBOL_UNIT_PARAMS {
  ///< Symbol used as reference for unit placement
  m_Symbol: SCH_SYMBOL | null;
  ///< Unit number to place; 0 means next available unit
  m_Unit: number;
}

'''


def unquote(text: str) -> str:
    """`_( "a" "b" )` - wxWidgets splits long strings across adjacent literals."""
    parts = re.findall(r'"((?:[^"\\]|\\.)*)"', text)
    s = ''.join(parts)
    return s


def ts_string(s: str) -> str:
    # C escapes are JS escapes for what appears here (\n, \", \\); keep them, quote with '.
    s = s.replace('\\"', '"')
    return "'" + s.replace("'", "\\'") + "'"


def hotkey(expr: str) -> str:
    expr = re.sub(r'static_cast<int>\(\s*(WXK_\w+)\s*\)', r'\1', expr)
    expr = re.sub(r"'(\\.|[^'])'", lambda m: f"ch('{m.group(1)}')" if m.group(1) != "\\'" else "ch(\"'\")", expr)
    expr = re.sub(r'\bWXK_(\w+)', r'WXK.WXK_\1', expr)
    return expr.strip()


def param(expr: str, consts: dict[str, str]) -> str:
    expr = expr.strip()
    if expr.startswith('&') and expr[1:] in consts:
        return consts[expr[1:]]
    if expr in ('nullptr',):
        return 'null'
    if expr == '{}':
        return '{}'
    m = re.fullmatch(r'SHAPE_T::(\w+)', expr)
    if m:
        return f'SHAPE_T.{m.group(1)}'
    m = re.fullmatch(r'LINE_MODE::(\w+)', expr)
    if m:
        return f'LINE_MODE.{m.group(1)}'
    if re.fullmatch(r'SCH_\w+_T', expr):
        return f'KICAD_T.{expr}'
    if re.fullmatch(r'-?\d+', expr):
        return expr
    raise ValueError(f'unhandled parameter {expr!r}')


def param_type(t: str | None) -> str:
    """The `.Parameter<T>( v )` template argument, where TS cannot infer it from the value."""
    if not t:
        return ''
    t = t.strip()
    table = {
        'int': '',
        'wxString*': '<string | null>',
        'DESIGN_BLOCK*': '<DESIGN_BLOCK | null>',
        'SCH_BITMAP*': '<SCH_BITMAP | null>',
        'SCH_ACTIONS::PLACE_SYMBOL_PARAMS': '<PLACE_SYMBOL_PARAMS>',
        'SCH_ACTIONS::PLACE_SYMBOL_UNIT_PARAMS': '<PLACE_SYMBOL_UNIT_PARAMS>',
    }
    if t not in table:
        raise ValueError(f'unhandled parameter type {t!r}')
    return table[t]


DEFAULTS = {
    '<PLACE_SYMBOL_PARAMS>': '{ m_Symbol: null, m_Reannotate: true }',
    '<PLACE_SYMBOL_UNIT_PARAMS>': '{ m_Symbol: null, m_Unit: 0 }',
}


def call(name: str, args: str, consts: dict[str, str]) -> str:
    a = args.strip()
    if name in ('Name', 'LegacyHotkeyName'):
        return f'.{name}({ts_string(unquote(a))})'
    if name in ('FriendlyName', 'Tooltip', 'MenuText', 'Description'):
        m = re.fullmatch(r'_\((.*)\)', a, re.S)
        return f'.{name}({ts_string(unquote(m.group(1) if m else a))})'
    if name == 'Scope':
        return f'.Scope(TOOL_ACTION_SCOPE.{a})'
    if name in ('DefaultHotkey', 'DefaultHotkeyAlt'):
        return f'.{name}({hotkey(a)})'
    if name == 'Icon':
        return f".Icon({a.replace('BITMAPS::', 'BITMAPS.')})"
    if name == 'Flags':
        flags = ' | '.join(f'TOOL_ACTION_FLAGS.{f.strip()}' for f in a.split('|'))
        return f'.Flags({flags})'
    if name == 'ToolbarState':
        return f".ToolbarState({a.replace('TOOLBAR_STATE::', 'TOOLBAR_STATE.')})"
    raise ValueError(f'unhandled builder call .{name}( {a} )')


def split_calls(body: str) -> list[tuple[str, str | None, str]]:
    """`.Name( x ) .Parameter<T>( y )` -> [(name, template, args)], parentheses balanced."""
    out = []
    i = 0
    while True:
        m = re.compile(r'\.(\w+)\s*(<[^>(]*>)?\s*\(').search(body, i)
        if not m:
            break
        depth = 1
        j = m.end()
        in_str = False
        while depth:
            c = body[j]
            if c == '"' and body[j - 1] != '\\':
                in_str = not in_str
            elif not in_str and c == '(':
                depth += 1
            elif not in_str and c == ')':
                depth -= 1
            j += 1
        tmpl = m.group(2)[1:-1] if m.group(2) else None
        out.append((m.group(1), tmpl, body[m.end():j - 1]))
        i = j
    return out


def main() -> None:
    # `// ...` comments can hold parentheses and quotes ("leave it as-is)"); none sits in a string.
    text = re.sub(r'//[^\n]*', '', REF.read_text())
    consts: dict[str, str] = {}
    for m in re.finditer(r'const DRAW_SEGMENT_EVENT_PARAMS (\w+) = \{ (\w+), (\w+), nullptr \};', text):
        consts[m.group(1)] = f'{{ layer: SCH_LAYER_ID.{m.group(2)}, quitOnDraw: {m.group(3)}, sourceSegment: null }}'

    members: list[str] = []
    for m in re.finditer(r'^TOOL_ACTION SCH_ACTIONS::(\w+)\(\s*TOOL_ACTION_ARGS\(\)(.*?)\);\s*$', text, re.S | re.M):
        name, body = m.group(1), m.group(2)
        lines = ['    new TOOL_ACTION_ARGS()']
        for cname, tmpl, args in split_calls(body):
            if cname == 'Parameter':
                t = param_type(tmpl)
                v = param(args, consts)
                if v == '{}':
                    v = DEFAULTS[t]
                lines.append(f'      .Parameter{t}({v})')
            else:
                lines.append('      ' + call(cname, args, consts))
        members.append(f'  static readonly {name} = new TOOL_ACTION(\n' + '\n'.join(lines) + ',\n  );\n')

    sys.stdout.write(HEADER)
    sys.stdout.write('export class SCH_ACTIONS extends ACTIONS {\n')
    sys.stdout.write('\n'.join(members))
    sys.stdout.write('}\n')
    print(f'{len(members)} actions', file=sys.stderr)


main()
