packages:
  - "common"
  - "eeschema"
  - "gerbview"
  - "bitmap2component"
  - "pagelayout_editor"
  - "cvpcb"
  - "pcbnew"
  - "3d-viewer"
  - "pcb_calculator"
  - "designer"
  - "ai"
  - "libs/*"
  - "bitmaps_png"
  - "qa"
  - "docs"
