// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * Which board layer each loaded Gerber goes to, the automatic half of
 * `DIALOG_MAP_GERBER_LAYERS_TO_PCB` (`gerbview/dialogs/dialog_map_gerber_layers_to_pcb.cpp`).
 *
 * Upstream shows a dialog with one row per loaded Gerber and a button to pick
 * the board layer by hand; before it does, `findKnownGerbersLoaded` (`:447-464`)
 * tries three exact-match tables in order and offers the result as an automatic
 * assignment. This module is those three tables and that ordering. It is NOT
 * the dialog: we have no mapping dialog, so the automatic answer is the only
 * answer, which is why {@link mapGerberLayersToPcb} also has to decide what
 * becomes of a row the user would otherwise have filled in by hand. See
 * {@link FALLBACK_USER_LAYERS}.
 *
 * The three tables are [data] in the CLAUDE.md sense: values KiCad hardcodes,
 * transcribed from its source rather than invented. The inner-copper runs are
 * generated by a loop, which is the same table — `In1_Cu … In30_Cu` and
 * `L2 … L30` and `G1 … G30` are consecutive in all three, and upstream only
 * spells them out because C++ has no better way to write a map literal.
 */

import { GERBER_FORMAT, type GERBER_FILE_IMAGE } from '@ziroeda/gerbview';
import {
  B_Adhes,
  B_Cu,
  B_CrtYd,
  B_Fab,
  B_Mask,
  B_Paste,
  B_SilkS,
  Cmts_User,
  CopperLayerToOrdinal,
  Dwgs_User,
  Eco1_User,
  Eco2_User,
  Edge_Cuts,
  F_Adhes,
  F_Cu,
  F_CrtYd,
  F_Fab,
  F_Mask,
  F_Paste,
  F_SilkS,
  In_Cu,
  IsCopperLayer,
  IsInnerCopperLayer,
  Margin,
  UNDEFINED_LAYER,
  UNSELECTED_LAYER,
} from '@ziroeda/pcbnew/src/layer_ids.js';

/**
 * `X2_ATTRIBUTE_FILEFUNCTION`'s three accessors, off the comma-separated
 * `%TF.FileFunction` value (`gerbview/X2_gerber_attributes.cpp:196-231`).
 *
 * `m_Prms.Item( 0 )` is the attribute name, which our parser has already
 * stripped (`gerbview/src/gerber_file_image_parse.ts:453`), so upstream's
 * `Item( 1 )` is our field 0 — the same offset `zOrderOf`
 * (`gerbview/src/layer_sort.ts:237`) reads. Upstream pads the parameter list to
 * seven entries in the constructor (`:139-141`) so a short attribute answers
 * the empty string rather than running off the end; `?? ''` is that padding.
 */
function x2Fields(fileFunction: string): { type: string; brdLayerId: string; side: string } {
  const p = fileFunction.split(',');
  const type = (p[0] ?? '').trim();
  const brdLayerId = (p[1] ?? '').trim();
  // `GetBrdLayerSide()`: Item( 3 ) for copper, Item( 2 ) otherwise — i.e. the
  // same field as GetBrdLayerId() for a non-copper file.
  const isCopper = type.toLowerCase() === 'copper';
  const side = isCopper ? (p[2] ?? '').trim() : brdLayerId;
  return { type, brdLayerId, side };
}

/** `X2_ATTRIBUTE_FILEFUNCTION::IsCopper()` (`X2_gerber_attributes.cpp:196`). */
function isCopperFunction(fileFunction: string): boolean {
  return x2Fields(fileFunction).type.toLowerCase() === 'copper';
}

/**
 * `X2_ATTRIBUTE_FILEFUNCTION::IsDrillFile()` (`X2_gerber_attributes.cpp:203`) —
 * a `%TF.FileFunction,Plated,…` or `,NonPlated,…` gerber.
 */
export function isDrillFileFunction(fileFunction: string | null): boolean {
  if (fileFunction === null) return false;
  const t = x2Fields(fileFunction).type.toLowerCase();
  return t === 'plated' || t === 'nonplated';
}

/**
 * `findNumX2GerbersLoaded`'s `kicadLayers` map
 * (`dialog_map_gerber_layers_to_pcb.cpp:711-758`), keyed exactly as upstream
 * keys it: on `GetBrdLayerSide()` for a copper file (falling back to
 * `GetBrdLayerId()` when the side reads `Inr`), and on `GetBrdLayerId()` and
 * `GetFileType()` concatenated for everything else — `"TopSoldermask"`,
 * `"BotPaste"`, `"PProfile"`.
 *
 * 45 entries: Top, L2…L30, Bot (31 copper) and 14 non-copper.
 */
export const X2_FILE_FUNCTION_LAYERS: ReadonlyMap<string, number> = new Map<string, number>([
  ['Top', F_Cu],
  // `{ wxT( "L2" ), In1_Cu } … { wxT( "L30" ), In29_Cu }` — L(n+1) is In(n).Cu,
  // because L1 is always the top copper layer.
  ...Array.from({ length: 29 }, (_, i): [string, number] => [`L${i + 2}`, In_Cu(i + 1)]),
  ['Bot', B_Cu],
  ['BotGlue', B_Adhes],
  ['TopGlue', F_Adhes],
  ['BotPaste', B_Paste],
  ['TopPaste', F_Paste],
  ['BotLegend', B_SilkS],
  ['TopLegend', F_SilkS],
  ['BotSoldermask', B_Mask],
  ['TopSoldermask', F_Mask],
  ['FabricationDrawing', Dwgs_User],
  ['OtherDrawing', Cmts_User],
  ['TopAssemblyDrawing', F_Fab],
  ['BotAssemblyDrawing', B_Fab],
  ['PProfile', Edge_Cuts], // Plated PCB outline
  ['NPProfile', Edge_Cuts], // Non-plated PCB outline
]);

/**
 * `findNumKiCadGerbersLoaded`'s `kicadLayers` map
 * (`dialog_map_gerber_layers_to_pcb.cpp:580-636`) — the suffix KiCad's plotter
 * appends to the project name, `-` included.
 *
 * 54 entries. Note the four aliases upstream carries for the layers whose
 * plotted name was lengthened (`-B_Adhesive` beside `-B_Adhes`,
 * `-F_Silkscreen` beside `-F_SilkS`) and that `-F_Courtyard` / `-B_Courtyard`
 * are spelled out while the layer id is `F_CrtYd` / `B_CrtYd`.
 */
export const KICAD_SUFFIX_LAYERS: ReadonlyMap<string, number> = new Map<string, number>([
  ['-F_Cu', F_Cu],
  ...Array.from({ length: 30 }, (_, i): [string, number] => [`-In${i + 1}_Cu`, In_Cu(i + 1)]),
  ['-B_Cu', B_Cu],
  ['-B_Adhes', B_Adhes],
  ['-F_Adhes', F_Adhes],
  ['-B_Adhesive', B_Adhes],
  ['-F_Adhesive', F_Adhes],
  ['-B_Paste', B_Paste],
  ['-F_Paste', F_Paste],
  ['-B_SilkS', B_SilkS],
  ['-F_SilkS', F_SilkS],
  ['-B_Silkscreen', B_SilkS],
  ['-F_Silkscreen', F_SilkS],
  ['-B_Mask', B_Mask],
  ['-F_Mask', F_Mask],
  ['-F_Fab', F_Fab],
  ['-B_Fab', B_Fab],
  ['-Dwgs_User', Dwgs_User],
  ['-Cmts_User', Cmts_User],
  ['-Eco1_User', Eco1_User],
  ['-Eco2_User', Eco2_User],
  ['-Edge_Cuts', Edge_Cuts],
  ['-Margin', Margin],
  ['-F_Courtyard', F_CrtYd],
  ['-B_Courtyard', B_CrtYd],
]);

/**
 * `findNumAltiumGerbersLoaded`'s `altiumExt` map
 * (`dialog_map_gerber_layers_to_pcb.cpp:473-515`) — the uppercased file
 * extension, no dot.
 *
 * 41 entries. `GM1`/`GM2` are Altium mechanical layers 1 and 2 and go to
 * `Eco1_User`/`Eco2_User`; `GKO` is the outline. There is no drill extension
 * in the table, which is one of the three reasons a `.drl` file reaches
 * `ExportPcb` unmapped.
 */
export const ALTIUM_EXTENSION_LAYERS: ReadonlyMap<string, number> = new Map<string, number>([
  ['GTL', F_Cu], // Top copper
  // "Inner layers 1 - 30"
  ...Array.from({ length: 30 }, (_, i): [string, number] => [`G${i + 1}`, In_Cu(i + 1)]),
  ['GBL', B_Cu], // Bottom copper
  ['GTP', F_Paste], // Paste top
  ['GBP', B_Paste], // Paste bottom
  ['GTO', F_SilkS], // Silkscreen top
  ['GBO', B_SilkS], // Silkscreen bottom
  ['GTS', F_Mask], // Soldermask top
  ['GBS', B_Mask], // Soldermask bottom
  ['GM1', Eco1_User], // Altium mechanical layer 1
  ['GM2', Eco2_User], // Altium mechanical layer 2
  ['GKO', Edge_Cuts], // PCB Outline
]);

/**
 * `wxFileName::GetName()` — the file name with the path and the extension
 * removed. Upstream builds a `wxFileName` from `m_FileName` before reading
 * either half (`:543`, `:664`).
 */
function fileNameBase(path: string): string {
  const base = stripDirs(path);
  const dot = base.lastIndexOf('.');
  return dot <= 0 ? base : base.slice(0, dot);
}

/** `wxFileName::GetExt()` — the text after the last dot, or the empty string. */
function fileNameExt(path: string): string {
  const base = stripDirs(path);
  const dot = base.lastIndexOf('.');
  return dot <= 0 ? '' : base.slice(dot + 1);
}

/**
 * The file name without any directory part. Both separators, because a name
 * that reached us through a browser upload can carry either.
 *
 * A leading dot is not an extension: `wxFileName` treats `.profile` as a name,
 * which is why both helpers above test `dot <= 0` rather than `dot < 0`.
 */
function stripDirs(path: string): string {
  return path.slice(Math.max(path.lastIndexOf('/'), path.lastIndexOf('\\')) + 1);
}

/**
 * `findNumX2GerbersLoaded` (`:705-832`), for one image.
 *
 * Guarded by `m_IsX2_file`, which upstream sets only once a `%TF` file
 * function has parsed (`gerbview/rs274x.cpp:395-397`) — our
 * `fileFunction !== null`, the same test `isX2File` already makes in
 * `gerberAuxControls.ts:318`. An Excellon image carries a *synthesised*
 * function (`Other,Drill`) but is not an X2 file upstream, so it is excluded
 * here; the point is moot in that `"Other" + "Drill"` matches no entry either
 * way, but the guard should say what upstream's says.
 */
function findX2Layer(image: GERBER_FILE_IMAGE): number {
  if (image.format === GERBER_FORMAT.EXCELLON) return UNSELECTED_LAYER;
  if (image.fileFunction === null) return UNSELECTED_LAYER;

  const f = x2Fields(image.fileFunction);
  let mapThis: string;

  if (isCopperFunction(image.fileFunction)) {
    // "Returns Top, Bot or Inr" — and an inner layer needs its number, so the
    // key falls back to the layer id ("L2", "L5", …).
    mapThis = f.side.toLowerCase() === 'inr' ? f.brdLayerId : f.side;
  } else {
    mapThis = f.brdLayerId + f.type;
  }

  return X2_FILE_FUNCTION_LAYERS.get(mapThis) ?? UNSELECTED_LAYER;
}

/**
 * `findNumKiCadGerbersLoaded` (`:574-702`), for one image.
 *
 * "KiCad appends a suffix consisting of a '-' and the name of the layer to the
 * project name. We need to isolate the suffix": the search is for the LAST
 * `-` in the name, and the suffix keeps the dash.
 */
function findKiCadSuffixLayer(image: GERBER_FILE_IMAGE): number {
  const layerName = fileNameBase(image.fileName);
  const dashPos = layerName.lastIndexOf('-');
  if (dashPos === -1) return UNSELECTED_LAYER;
  return KICAD_SUFFIX_LAYERS.get(layerName.slice(dashPos)) ?? UNSELECTED_LAYER;
}

/** `findNumAltiumGerbersLoaded` (`:467-571`), for one image. */
function findAltiumExtensionLayer(image: GERBER_FILE_IMAGE): number {
  return ALTIUM_EXTENSION_LAYERS.get(fileNameExt(image.fileName).toUpperCase()) ?? UNSELECTED_LAYER;
}

/**
 * `findKnownGerbersLoaded` (`:447-464`): the three tables in order, first
 * claim wins.
 *
 * Upstream's ordering is not incidental. Each finder skips a row that is
 * already something other than `UNSELECTED_LAYER` ("This will preserve them"),
 * so an X2 attribute beats a KiCad file name, which beats an Altium extension.
 * A KiCad-plotted X2 gerber matches the first two and must take the first.
 */
export function findKnownGerberLayer(image: GERBER_FILE_IMAGE): number {
  const x2 = findX2Layer(image);
  if (x2 !== UNSELECTED_LAYER) return x2;

  const kicad = findKiCadSuffixLayer(image);
  if (kicad !== UNSELECTED_LAYER) return kicad;

  return findAltiumExtensionLayer(image);
}

/**
 * Where an unmatched Gerber goes, in order.
 *
 * **This is a divergence, deliberately.** Upstream leaves an unmatched row at
 * `UNSELECTED_LAYER` and colours it blue "Do not export"; `ExportPcb` then
 * drops it (`export_to_pcbnew.cpp:111-112`). That is only safe because a human
 * is looking at the dialog and can assign the layer by hand before pressing
 * OK. We have no such dialog, so honouring `UNSELECTED_LAYER` would mean a
 * one-click export that silently omits layers with no way to get them back —
 * the worse of the two failures. A wrong-but-visible layer can be seen in
 * pcbnew and moved; a missing one cannot.
 *
 * These are KiCad's four general-purpose user layers, `Dwgs_User`,
 * `Cmts_User`, `Eco1_User` and `Eco2_User` — the same four `LSET::UserMask()`
 * lists ahead of `Edge_Cuts` and `Margin`, which are not general-purpose. They
 * are handed out one per unmatched layer rather than indexed by the layer's
 * position, so three unmatched layers get three distinct destinations instead
 * of colliding; past the fourth they do repeat, and there is nowhere else for
 * them to go.
 */
export const FALLBACK_USER_LAYERS: readonly number[] = [Dwgs_User, Cmts_User, Eco1_User, Eco2_User];

/** One row of the mapping: what `aLayerLookUpTable[layer]` holds, plus why. */
export interface GerberLayerMapping {
  /** The `PCB_LAYER_ID` for this image, or `UNSELECTED_LAYER`/`UNDEFINED_LAYER`. */
  pcbLayer: number;
  /** True when no table claimed it and {@link FALLBACK_USER_LAYERS} chose. */
  fallback: boolean;
}

/** What {@link mapGerberLayersToPcb} answers: the lookup table and the stack. */
export interface GerberLayerMap {
  rows: GerberLayerMapping[];
  /**
   * `DIALOG_MAP_GERBER_LAYERS_TO_PCB::m_exportBoardCopperLayersCount`, which
   * `ExportPcb` takes as `aCopperLayers` and `writePcbHeader` turns into
   * `LSET::AllCuMask( m_pcbCopperLayersCount )`.
   */
  copperLayerCount: number;
}

/**
 * `normalizeBrdLayersCount` (`:255-266`): even, at least 2, at most
 * `GERBER_DRAWLAYERS_COUNT`.
 */
function normalizeBrdLayersCount(count: number): number {
  let n = count;
  if (n & 1) n++;
  // GERBER_DRAWLAYERS_COUNT, which is 32 and equals MAX_CU_LAYERS.
  if (n > 32) n = 32;
  if (n < 2) n = 2;
  return n;
}

/**
 * The whole automatic assignment: `findKnownGerbersLoaded`, then the block
 * `initDialog` runs when the user accepts it (`:220-249`), then
 * `normalizeBrdLayersCount`.
 *
 * Two things happen here that upstream leaves to a human:
 *
 * 1. An unmatched plain Gerber is given a user drawing layer instead of being
 *    dropped — see {@link FALLBACK_USER_LAYERS}.
 * 2. An Excellon drill file, and a gerber whose X2 attribute says it is a
 *    drill file (`IsDrillFile()`), are mapped to `UNDEFINED_LAYER`, the value
 *    the dialog's "Hole Data" row returns. `ExportPcb` reads that as "collect
 *    these as holes" (`export_to_pcbnew.cpp:89-93`) and their geometry becomes
 *    vias and slots. This one is also a divergence — upstream would leave both
 *    at `UNSELECTED_LAYER` until a human picked Hole Data — but the *opposite*
 *    choice is not available to us: giving a drill file a fallback graphics
 *    layer would draw its holes as circles AND (for the Excellon case) export
 *    them as vias, double-exporting the file.
 *
 * The copper count follows upstream exactly where it can:
 * `std::max( total_copper, 2 )` (`:246`). Upstream then *refuses* the export
 * with "Exported board does not have enough copper layers to handle selected
 * inner layers" if a mapped inner layer does not fit (`:436-441`); with no
 * dialog to return to there is nothing to refuse into, so the count is grown
 * to fit instead. That check is `CopperLayerToOrdinal( inner_layer_max ) >
 * count - 2`, so the count that satisfies it is `ordinal + 2`.
 */
export function mapGerberLayersToPcb(images: readonly GERBER_FILE_IMAGE[]): GerberLayerMap {
  const rows: GerberLayerMapping[] = [];
  let fallbackUsed = 0;

  for (const image of images) {
    if (image.format === GERBER_FORMAT.EXCELLON || isDrillFileFunction(image.fileFunction)) {
      rows.push({ pcbLayer: UNDEFINED_LAYER, fallback: false });
      continue;
    }

    const known = findKnownGerberLayer(image);

    if (known === UNSELECTED_LAYER) {
      const layer = FALLBACK_USER_LAYERS[fallbackUsed % FALLBACK_USER_LAYERS.length]!;
      fallbackUsed++;
      rows.push({ pcbLayer: layer, fallback: true });
    } else {
      rows.push({ pcbLayer: known, fallback: false });
    }
  }

  // "Reset the number of copper layers to the total found" (:245-248).
  let totalCopper = 0;
  let innerLayerMax = 0;

  for (const row of rows) {
    if (IsCopperLayer(row.pcbLayer)) totalCopper++;
    if (IsInnerCopperLayer(row.pcbLayer) && row.pcbLayer > innerLayerMax)
      innerLayerMax = row.pcbLayer;
  }

  let copperLayerCount = Math.max(totalCopper, 2);

  if (innerLayerMax > 0)
    copperLayerCount = Math.max(copperLayerCount, CopperLayerToOrdinal(innerLayerMax) + 2);

  return { rows, copperLayerCount: normalizeBrdLayersCount(copperLayerCount) };
}
