M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-28T08:25:58
; FORMAT={3:3/ absolute / metric / suppress trailing zeros}
; #@! TF.CreationDate,2026-09-28T08:25:58+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,MixedPlating,1,4
FMAT,2
METRIC,LZ
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C1.200
%
G90
G05
T1
X014Y029
T2
X01Y01
X028Y007
T4
X04Y02754
T5
X04Y03008
X04Y025
T6
X026Y025
T3
X039654Y03496G85X040346Y03536
G05
X0396Y03262G85X0404Y03262
G05
M30
