// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from Zint (BSD-3-Clause), copyright Robin Stuart and
// contributors. See NOTICE.md.
/**
 * Reed-Solomon error correction, from Zint's `backend/reedsol.c`.
 *
 * Shared by QR, Micro QR and Data Matrix — the three symbologies of KiCad's
 * five that carry error correction at all. Code 39 and Code 128 have only a
 * check digit and never come here.
 *
 * The Galois-field log tables are computed rather than transcribed. Upstream
 * ships them as literals in `reedsol_logs.h`, generated by
 * `backend/tests/test_reedsol -f generate -g` from the prime polynomial and
 * pasted in; the generation rule is the definition, so computing it here is
 * the same table by construction and not a re-derivation. `reedsol.test.ts`
 * checks ours against the header's literals for both polynomials, so the claim
 * is pinned rather than asserted.
 */

/** The prime polynomials `rs_init_gf` is called with, by symbology. */
export const GF_QR = 0x11d; // a**8 + a**4 + a**3 + a**2 + 1
export const GF_DATAMATRIX = 0x12d; // a**8 + a**5 + a**3 + a**2 + 1

interface GaloisField {
  /** `logt`, 256 entries. `logt[0]` is 0: "for simplicity allow log of 0". */
  logt: Uint8Array;
  /** `alog`, 510 entries — the 255-entry cycle doubled, so `alog[a + b]` needs no modulo. */
  alog: Uint8Array;
}

const FIELDS = new Map<number, GaloisField>();

/**
 * `rs_init_gf( rs, prime_poly )` (`reedsol.c:67-96`), which upstream resolves
 * to a pre-generated pair of tables. Same tables, built on first use and
 * cached: there are two polynomials in play and each is built once per process.
 */
function galoisField(primePoly: number): GaloisField {
  const cached = FIELDS.get(primePoly);
  if (cached) return cached;

  const logt = new Uint8Array(256);
  const alog = new Uint8Array(510);
  let x = 1;

  for (let i = 0; i < 255; i++) {
    alog[i] = x;
    alog[i + 255] = x;
    logt[x] = i;
    x <<= 1;
    if (x & 0x100) x ^= primePoly;
  }

  const field = { logt, alog };
  FIELDS.set(primePoly, field);
  return field;
}

/**
 * `rs_init_code( rs, nsym, index )` (`reedsol.c:104-136`): the generator
 * polynomial `(x + 2**index)(x + 2**(index+1))…`, `nsym` terms.
 *
 * `index` is 1 for every caller here — QR, Micro QR and Data Matrix all use
 * it — but it is a parameter upstream and stays one.
 */
export class ReedSolomon {
  private readonly logt: Uint8Array;
  private readonly alog: Uint8Array;
  private readonly rspoly: Uint8Array;
  private readonly logRspoly: Uint8Array;
  private readonly zero: boolean;
  readonly nsym: number;

  constructor(primePoly: number, nsym: number, index = 1) {
    const { logt, alog } = galoisField(primePoly);
    this.logt = logt;
    this.alog = alog;
    this.nsym = nsym;

    const rspoly = new Uint8Array(nsym + 1);
    rspoly[0] = 1;

    for (let i = 1; i <= nsym; i++) {
      rspoly[i] = 1;
      for (let k = i - 1; k > 0; k--) {
        // Multiply coeff by 2**index, then add coeff of x**(k-1) * x.
        if (rspoly[k]) rspoly[k] = alog[logt[rspoly[k]!]! + index]!;
        rspoly[k]! ^= rspoly[k - 1]!;
      }
      rspoly[0] = alog[logt[rspoly[0]!]! + index]!;
      index++;
    }

    // "Set logs of poly and check if have zero coeffs".
    const logRspoly = new Uint8Array(nsym + 1);
    let zero = false;
    for (let i = 0; i <= nsym; i++) {
      logRspoly[i] = logt[rspoly[i]!]!;
      zero ||= rspoly[i] === 0;
    }

    this.rspoly = rspoly;
    this.logRspoly = logRspoly;
    this.zero = zero;
  }

  /**
   * `rs_encode( rs, datalen, data, res )` (`reedsol.c:138-186`): the `nsym`
   * check codewords for `data`, most significant first.
   *
   * Upstream splits the loop in two to keep a branch out of the inner one when
   * the polynomial has no zero coefficient. That is a speed shape, not a
   * semantic one, so there is one loop here and `zero` guards inside it — the
   * two produce identical output, which is what `reedsol.test.ts` checks by
   * running both kinds of polynomial.
   */
  encode(data: Uint8Array | readonly number[]): Uint8Array {
    const { logt, alog, rspoly, logRspoly, nsym } = this;
    const res = new Uint8Array(nsym);

    for (let i = 0; i < data.length; i++) {
      const m = res[nsym - 1]! ^ data[i]!;
      if (m) {
        const logM = logt[m]!;
        for (let k = nsym - 1; k > 0; k--) {
          res[k] =
            this.zero && !rspoly[k] ? res[k - 1]! : res[k - 1]! ^ alog[logM + logRspoly[k]!]!;
        }
        res[0] = alog[logM + logRspoly[0]!]!;
      } else {
        res.copyWithin(1, 0, nsym - 1);
        res[0] = 0;
      }
    }

    return res.reverse();
  }
}
