// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * `gal/cursors.h`: the cursor ids. `CURSOR_STORE` (the XPM/PNG bundles behind
 * them) is the window's; the editors' `cursors.ts` map these to CSS cursors.
 */

export enum KICURSOR {
  DEFAULT,
  ARROW,
  ARROW64,
  MOVING,
  MOVING64,
  WARNING,
  WARNING64,
  PENCIL,
  PENCIL64,
  REMOVE,
  REMOVE64,
  HAND,
  HAND64,
  BULLSEYE,
  BULLSEYE64,
  VOLTAGE_PROBE,
  VOLTAGE_PROBE64,
  CURRENT_PROBE,
  CURRENT_PROBE64,
  TUNE,
  TUNE64,
  TEXT,
  TEXT64,
  MEASURE,
  MEASURE64,
  ADD,
  ADD64,
  SUBTRACT,
  SUBTRACT64,
  XOR,
  XOR64,
  ZOOM_IN,
  ZOOM_IN64,
  ZOOM_OUT,
  ZOOM_OUT64,
  LABEL_NET,
  LABEL_NET64,
  LABEL_GLOBAL,
  LABEL_GLOBAL64,
  COMPONENT,
  COMPONENT64,
  SELECT_WINDOW,
  SELECT_WINDOW64,
  SELECT_LASSO,
  SELECT_LASSO64,
  LINE_BUS,
  LINE_BUS64,
  LINE_GRAPHIC,
  LINE_GRAPHIC64,
  LINE_WIRE,
  LINE_WIRE64,
  LABEL_HIER,
  LABEL_HIER64,
  PLACE,
  PLACE64,
}
