// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * The SPECCTRA DSN export against KiCad 10.0.6's own: `pcbnew.ExportSpecctraDSN`
 * over the same board (`qa/data/pcbnew/specctra_oracle/`, regenerated by its
 * `regen.py`), whole file, line for line. The first line (the file path) and
 * the `host_version` line (the build string) are masked; everything else, the
 * padstack names and the netclass order included, is compared as written.
 *
 * The reader is checked against the same files: parse the DSN KiCad wrote and
 * format it back, which must give the bytes it started from.
 */
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { ParseBoard } from '@ziroeda/pcbnew/pcb_io/kicad_sexpr/pcb_io_kicad_sexpr.js';
import { ExportBoardToSpecctraFile } from '@ziroeda/pcbnew/specctra_import_export/specctra_export.js';
import { SPECCTRA_DB } from '@ziroeda/pcbnew/specctra_import_export/specctra.js';
import { PCB_LAYER_ID } from '@ziroeda/common/layer_id.js';
import type { BOARD } from '@ziroeda/pcbnew/board.js';
import { KICAD_T } from '@ziroeda/core/typeinfo.js';
import type { PCB_ARC, PCB_VIA } from '@ziroeda/pcbnew/pcb_track.js';
import { ImportSpecctraSession } from '@ziroeda/pcbnew/specctra_import_export/specctra_import.js';

const DIR = new URL('../../data/pcbnew/specctra_oracle/', import.meta.url).pathname;
const BOARDS = new URL('../../data/pcbnew/resave/', import.meta.url).pathname;

const mask = (text: string): string =>
  text
    .replace(/^\(pcb .*$/m, '(pcb <file>')
    .replace(/^ {4}\(host_version .*$/m, '    (host_version <build>)');

// `One-Air-Max` is checked by the reader only: its board outline is arcs, and
// `BuildBoardPolygonOutlines` puts a few of the arc vertices 0.1 um from where
// KiCad's do (16 of its 4000 lines differ, all outline points). That is the
// outline builder's, not this exporter's; the reader half still covers the file.
const NAMES = [
  'ecc83-pp',
  'interf_u',
  'blindvias_kicad_cli',
  'blindvias2_kicad_cli',
  'custompads_kicad_cli',
  'StickHub_kicad_cli',
  'hatchpads_kicad_cli',
  'waveorder_kicad_cli',
];

describe('DSN export, against pcbnew.ExportSpecctraDSN', () => {
  for (const name of NAMES) {
    it(`${name}.dsn matches line for line`, () => {
      const board = ParseBoard(readFileSync(`${BOARDS}${name}.kicad_pcb`, 'utf8'));
      const { text } = ExportBoardToSpecctraFile(board, `${name}.dsn`);
      const want = readFileSync(`${DIR}${name}.dsn`, 'utf8');

      const a = mask(text).split('\n');
      const b = mask(want).split('\n');
      const at = a.findIndex((l, i) => l !== b[i]);

      expect(at < 0 ? '' : `line ${at + 1}:\n ours: ${a[at]}\n want: ${b[at]}`).toBe('');
      expect(a.length).toBe(b.length);
    });
  }
});

describe('DSN reader, against the same files', () => {
  for (const name of [...NAMES, 'One-Air-Max']) {
    it(`${name}.dsn parses and formats back to itself`, () => {
      const want = readFileSync(`${DIR}${name}.dsn`, 'utf8');
      const db = new SPECCTRA_DB();

      db.LoadPCB(want, `${name}.dsn`);

      const text = db.ExportPCB()!;

      expect(mask(text)).toBe(mask(want));
    });
  }
});

// ----- the session import, against pcbnew.ImportSpecctraSES -----

const dump = (b: BOARD) => ({
  tracks: b.Tracks().map((t) => {
    const d: Record<string, unknown> = {
      type:
        t.Type() === KICAD_T.PCB_VIA_T
          ? 'PCB_VIA'
          : t.Type() === KICAD_T.PCB_ARC_T
            ? 'PCB_ARC'
            : 'PCB_TRACK',
      layer: b.GetLayerName(t.GetLayer()),
      net: t.GetNetname(),
      locked: t.IsLocked(),
    };
    if (t.Type() === KICAD_T.PCB_VIA_T) {
      const v = t as PCB_VIA;
      Object.assign(d, {
        width: v.GetWidth(PCB_LAYER_ID.F_Cu),
        pos: [v.GetPosition().x, v.GetPosition().y],
        drill: v.GetDrillValue(),
        viatype: v.GetViaType(),
        top: b.GetLayerName(v.TopLayer()),
        bottom: b.GetLayerName(v.BottomLayer()),
      });
    } else {
      d.width = t.GetWidth();
      d.start = [t.GetStart().x, t.GetStart().y];
      d.end = [t.GetEnd().x, t.GetEnd().y];
      if (t.Type() === KICAD_T.PCB_ARC_T)
        d.mid = [(t as PCB_ARC).GetMid().x, (t as PCB_ARC).GetMid().y];
    }
    return d;
  }),
  footprints: b.Footprints().map((f) => ({
    ref: f.GetReference(),
    pos: [f.GetPosition().x, f.GetPosition().y],
    deg: f.GetOrientationDegrees(),
    layer: b.GetLayerName(f.GetLayer()),
  })),
});

const key = (o: Record<string, unknown>): string => JSON.stringify(o, Object.keys(o).sort());

describe('SES import, against pcbnew.ImportSpecctraSES', () => {
  it('ecc83-pp.ses: the tracks, vias and placements pcbnew ends up with', () => {
    const board = ParseBoard(readFileSync(`${BOARDS}ecc83-pp.kicad_pcb`, 'utf8'));
    const skipped = ImportSpecctraSession(
      board,
      readFileSync(`${DIR}ecc83-pp.ses`, 'utf8'),
      'ecc83-pp.ses',
    );
    const want = JSON.parse(readFileSync(`${DIR}ecc83-pp.ses.expected.json`, 'utf8')) as {
      ok: boolean;
      tracks: Record<string, unknown>[];
      footprints: Record<string, unknown>[];
    };
    const got = dump(board);

    expect(want.ok).toBe(true);
    // the unresolved component, the unknown layer and the unknown padstack
    expect(skipped).toBe(3);
    expect(got.tracks.map(key).sort()).toEqual(want.tracks.map(key).sort());
    expect(got.footprints.map(key).sort()).toEqual(want.footprints.map(key).sort());
  });
});
