M48
; DRILL file KiCad 10.0.6-10.0.6~ubuntu24.04.1 date 2026-09-28T08:25:58
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-28T08:25:58+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6-10.0.6~ubuntu24.04.1
; #@! TF.FileFunction,Plated,1,4,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T2C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.800
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C1.000
%
G90
G05
T1
X34.0Y-26.0
T2
X30.0Y-45.0
X48.0Y-48.0
T4
X60.0Y-27.46
T5
X60.0Y-24.92
X60.0Y-30.0
T3
X59.654Y-20.04G85X60.346Y-19.64
G05
X59.6Y-22.38G85X60.4Y-22.38
G05
M30
