// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * SCH_ACTIONS (tools/sch_actions.cpp), generated by tools/kicad/port_sch_actions.py: spot checks
 * of the builder calls it translates, against the C++.
 */
import { WXK } from '@ziroeda/core/wx_keycodes.js';
import { KICAD_T } from '@ziroeda/core/typeinfo.js';
import { SHAPE_T } from '@ziroeda/common/eda_shape.js';
import { SCH_LAYER_ID } from '@ziroeda/common/layer_id.js';
import { TOOL_ACTION } from '@ziroeda/common/tool/tool_action.js';
import { TOOL_ACTION_SCOPE } from '@ziroeda/common/tool/tool_action.js';
import { MD_ALT, MD_CTRL, MD_SHIFT } from '@ziroeda/common/tool/tool_event.js';
import { LINE_MODE, SCH_ACTIONS } from '@ziroeda/eeschema/tools/sch_actions.js';
import { describe, expect, it } from 'vitest';

const own = Object.getOwnPropertyNames(SCH_ACTIONS)
  .map((k) => (SCH_ACTIONS as unknown as Record<string, unknown>)[k])
  .filter((v): v is TOOL_ACTION => v instanceof TOOL_ACTION);

describe('SCH_ACTIONS', () => {
  it('has every action sch_actions.cpp defines', () => {
    expect(own).toHaveLength(226);
  });

  it('keeps the name, scope, hotkey, label, flags and parameter of each', () => {
    // sch_actions.cpp:1479 drawWire
    const w = SCH_ACTIONS.drawWire;
    expect(w.GetName()).toBe('eeschema.InteractiveDrawingLineWireBus.drawWires');
    expect(w.GetScope()).toBe(TOOL_ACTION_SCOPE.AS_GLOBAL);
    expect(w.GetDefaultHotKey()).toBe('W'.charCodeAt(0));
    expect(w.GetFriendlyName()).toBe('Draw Wires');
    expect(w.IsActivation()).toBe(true);
    expect(w.GetParam()).toEqual({
      layer: SCH_LAYER_ID.LAYER_WIRE,
      quitOnDraw: false,
      sourceSegment: null,
    });
    expect(SCH_ACTIONS.drawLines.GetParam()).toMatchObject({ layer: SCH_LAYER_ID.LAYER_NOTES });
  });

  it('spells modifier hotkeys and named keys as the C++ does', () => {
    expect(SCH_ACTIONS.selectNode.GetDefaultHotKey()).toBe(MD_ALT + '3'.charCodeAt(0));
    expect(SCH_ACTIONS.selectConnection.GetDefaultHotKey()).toBe(MD_CTRL + '4'.charCodeAt(0));
    expect(SCH_ACTIONS.undoLastSegment.GetDefaultHotKey()).toBe(WXK.WXK_BACK);
    const shifted = [...own].find(
      (a) => a.GetDefaultHotKey() === MD_CTRL + MD_SHIFT + 'F'.charCodeAt(0),
    );
    expect(shifted).toBeTruthy();
  });

  it('translates the typed parameters', () => {
    expect(SCH_ACTIONS.toHLabel.GetParam()).toBe(KICAD_T.SCH_HIER_LABEL_T);
    expect(SCH_ACTIONS.toDLabel.GetParam()).toBe(KICAD_T.SCH_DIRECTIVE_LABEL_T);
    expect(SCH_ACTIONS.placeHierLabel.HasParam()).toBe(false);
    expect(SCH_ACTIONS.drawRectangle.GetParam()).toBe(SHAPE_T.RECTANGLE);
    expect(SCH_ACTIONS.lineMode90.GetParam()).toBe(LINE_MODE.LINE_MODE_90);
    expect(SCH_ACTIONS.placeSymbol.GetParam()).toEqual({ m_Symbol: null, m_Reannotate: true });
  });

  it('joins a tooltip split across adjacent literals', () => {
    expect(SCH_ACTIONS.selectConnection.GetTooltip(false)).toBe(
      'Selects a connection or expands an existing selection to pins, symbols, or entire connections',
    );
  });
});
