// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 ZiroEDA and contributors.
// Portions derived from KiCad, copyright The KiCad Developers. See NOTICE.md.
/**
 * `SCH_ACTIONS` (eeschema/tools/sch_actions.h, sch_actions.cpp): every tool action of the
 * schematic and symbol editors, each a static TOOL_ACTION registered with ACTION_MANAGER as it is
 * built, exactly as the C++ statics are. The strings are the C++'s untranslated `_()` sources.
 * GENERATED by tools/kicad/port_sch_actions.py from sch_actions.cpp (KiCad 10.0.6); edit the
 * generator, not this file.
 */
import { WXK } from '@ziroeda/core/wx_keycodes.js';
import { KICAD_T } from '@ziroeda/core/typeinfo.js';
import { BITMAPS } from '@ziroeda/common/bitmaps/bitmaps_list.js';
import { SHAPE_T } from '@ziroeda/common/eda_shape.js';
import { SCH_LAYER_ID } from '@ziroeda/common/layer_id.js';
import { ACTIONS } from '@ziroeda/common/tool/actions.js';
import {
  TOOL_ACTION,
  TOOL_ACTION_ARGS,
  TOOL_ACTION_FLAGS,
  TOOL_ACTION_SCOPE,
  TOOLBAR_STATE,
} from '@ziroeda/common/tool/tool_action.js';
import { MD_ALT, MD_CTRL, MD_SHIFT } from '@ziroeda/common/tool/tool_event.js';
import type { SCH_BITMAP } from '../sch_bitmap.js';
import type { SCH_LINE } from '../sch_line.js';
import type { SCH_SYMBOL } from '../sch_symbol.js';

/** `'N'` in a hotkey: the character's code, as C++ `int` promotion gives it. */
const ch = (c: string): number => c.charCodeAt(0);

/** `LINE_MODE` (eeschema_settings.h:45). */
export enum LINE_MODE {
  LINE_MODE_FREE = 0,
  LINE_MODE_90 = 1,
  LINE_MODE_45 = 2,

  LINE_MODE_COUNT,
}

/** `DRAW_SEGMENT_EVENT_PARAMS` (tools/sch_line_wire_bus_tool.h:62). */
export interface DRAW_SEGMENT_EVENT_PARAMS {
  layer: SCH_LAYER_ID;
  quitOnDraw: boolean;
  sourceSegment: SCH_LINE | null;
}

/** `DESIGN_BLOCK` (common/design_block.h): pending with the design-block library. */
export type DESIGN_BLOCK = unknown;

/** `SCH_ACTIONS::PLACE_SYMBOL_PARAMS` (sch_actions.h:330). */
export interface PLACE_SYMBOL_PARAMS {
  ///< Provide a symbol to place
  m_Symbol: SCH_SYMBOL | null;
  ///< If a symbol is provide, reannotate it?
  m_Reannotate: boolean;
}

/** `SCH_ACTIONS::PLACE_SYMBOL_UNIT_PARAMS` (sch_actions.h:338). */
export interface PLACE_SYMBOL_UNIT_PARAMS {
  ///< Symbol used as reference for unit placement
  m_Symbol: SCH_SYMBOL | null;
  ///< Unit number to place; 0 means next available unit
  m_Unit: number;
}

export class SCH_ACTIONS extends ACTIONS {
  static readonly runERC = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InspectionTool.runERC')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Electrical Rules Checker')
      .Tooltip('Show the electrical rules checker window')
      .Icon(BITMAPS.erc),
  );

  static readonly checkSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InspectionTool.checkSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Symbol Checker')
      .Tooltip('Show the symbol checker window')
      .Icon(BITMAPS.erc),
  );

  static readonly diffSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InspectionTool.diffSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Compare Symbol with Library')
      .Tooltip('Show differences between schematic symbol and its library equivalent')
      .Icon(BITMAPS.library),
  );

  static readonly showBusSyntaxHelp = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InspectionTool.showBusSyntaxHelp')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Bus Syntax Help')
      .Icon(BITMAPS.bus_definition_tool),
  );

  static readonly showSimulator = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showSimulator')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Simulator')
      .Tooltip('Show simulation window for running SPICE or IBIS simulations.')
      .Icon(BITMAPS.simulator),
  );

  static readonly pointEditorAddCorner = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.PointEditor.addCorner')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Create Corner')
      .Icon(BITMAPS.add_corner),
  );

  static readonly pointEditorRemoveCorner = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.PointEditor.removeCorner')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Remove Corner')
      .Icon(BITMAPS.delete_cursor),
  );

  static readonly selectNode = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveSelection.SelectNode')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_ALT + ch('3'))
      .LegacyHotkeyName('Select Node')
      .FriendlyName('Select Node')
      .Tooltip('Select a connection item under the cursor'),
  );

  static readonly selectConnection = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveSelection.SelectConnection')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('4'))
      .LegacyHotkeyName('Select Connection')
      .FriendlyName('Select/Expand Connection')
      .Tooltip(
        'Selects a connection or expands an existing selection to pins, symbols, or entire connections',
      )
      .Icon(BITMAPS.net_highlight_schematic),
  );

  static readonly syncSelection = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveSelection.SyncSelection')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL),
  );

  static readonly showDesignBlockPanel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SchDesignBlockControl.showDesignBlockPanel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Design Blocks')
      .Tooltip('Show/hide design blocks library')
      .Icon(BITMAPS.search_tree),
  );

  static readonly showRemoteSymbolPanel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.RemoteSymbols.showPanel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Remote Symbols')
      .Tooltip('Show/hide the remote symbol panel')
      .Icon(BITMAPS.library_browser),
  );

  static readonly saveSheetAsDesignBlock = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SchDesignBlockControl.saveSheetAsDesignBlock')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Save Current Sheet as Design Block...')
      .Tooltip('Create a new design block from the current sheet')
      .Icon(BITMAPS.new_component),
  );

  static readonly saveSelectionAsDesignBlock = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SchDesignBlockControl.saveSelectionAsDesignBlock')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Save Selection as Design Block...')
      .Tooltip('Create a new design block from the current selection')
      .Icon(BITMAPS.new_component),
  );

  static readonly updateDesignBlockFromSheet = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SchDesignBlockControl.updateDesignBlockFromSheet')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Update Design Block from Current Sheet')
      .Tooltip('Set design block schematic to current sheet')
      .Icon(BITMAPS.save),
  );

  static readonly updateDesignBlockFromSelection = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SchDesignBlockControl.updateDesignBlockFromSelection')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Update Design Block from Selection')
      .Tooltip('Set design block schematic to current selection')
      .Icon(BITMAPS.save),
  );

  static readonly deleteDesignBlock = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SchDesignBlockControl.deleteDesignBlock')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Delete Design Block')
      .Tooltip('Remove the selected design block from its library')
      .Icon(BITMAPS.trash),
  );

  static readonly editDesignBlockProperties = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SchDesignBlockControl.editDesignBlockProperties')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Properties...')
      .Tooltip('Edit properties of design block')
      .Icon(BITMAPS.edit),
  );

  static readonly saveLibraryAs = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.saveLibraryAs')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + MD_SHIFT + ch('S'))
      .LegacyHotkeyName('Save As')
      .FriendlyName('Save Library As...')
      .Tooltip('Save the current library to a new file'),
  );

  static readonly newSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.newSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('N'))
      .FriendlyName('New Symbol...')
      .Tooltip('Create a new symbol in an existing library')
      .Icon(BITMAPS.new_component),
  );

  static readonly deriveFromExistingSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.deriveFromExistingSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Derive from Existing Symbol...')
      .Tooltip('Create a new symbol, derived from an existing symbol')
      .Icon(BITMAPS.new_component),
  );

  static readonly editSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.editSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Edit Symbol')
      .Tooltip('Show selected symbol on editor canvas')
      .Icon(BITMAPS.edit),
  );

  static readonly duplicateSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.duplicateSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Duplicate Symbol')
      .Icon(BITMAPS.duplicate),
  );

  static readonly renameSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.renameFootprint')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Rename Symbol...')
      .Icon(BITMAPS.edit),
  );

  static readonly saveSymbolAs = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.saveSymbolAs')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Save As...')
      .Tooltip('Save the current symbol to a different library or name')
      .Icon(BITMAPS.save_as),
  );

  static readonly saveSymbolCopyAs = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.saveSymbolCopyAs')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Save Copy As...')
      .Tooltip('Save a copy of the current symbol to a different library or name')
      .Icon(BITMAPS.save_as),
  );

  static readonly deleteSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.deleteSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Delete Symbol')
      .Tooltip('Remove the selected symbol from its library')
      .Icon(BITMAPS.trash),
  );

  static readonly cutSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.cutSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Cut')
      .Icon(BITMAPS.cut),
  );

  static readonly copySymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.copySymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Copy')
      .Icon(BITMAPS.copy),
  );

  static readonly pasteSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.pasteSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Paste Symbol')
      .Icon(BITMAPS.paste),
  );

  static readonly importSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.importSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Import Symbol...')
      .Tooltip('Import a symbol to the current library')
      .Icon(BITMAPS.import_part),
  );

  static readonly exportSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.exportSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export...')
      .Tooltip('Export a symbol to a new library file')
      .Icon(BITMAPS.export_part),
  );

  static readonly updateSymbolFields = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.updateSymbolFields')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Update Symbol Fields...')
      .Tooltip('Update symbol to match changes made in parent symbol')
      .Icon(BITMAPS.refresh),
  );

  static readonly flattenSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.flattenSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Flatten Symbol')
      .Tooltip('Remove inheritance from symbol'),
  );

  static readonly showLibFieldsTable = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.showLibraryFieldsTable')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Bulk Edit Symbol Fields...')
      .Tooltip('Edit a table of fields from all symbols in the library')
      .Icon(BITMAPS.table),
  );

  static readonly showRelatedLibFieldsTable = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.showRelatedLibraryFieldsTable')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Bulk Edit Related Symbol Fields...')
      .Tooltip('Edit a table of fields from all symbols related to the selected symbol')
      .Icon(BITMAPS.table),
  );

  static readonly addSymbolToSchematic = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.addSymbolToSchematic')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Add Symbol to Schematic')
      .Tooltip('Add the current symbol to the schematic')
      .Icon(BITMAPS.add_symbol_to_schematic),
  );

  static readonly showElectricalTypes = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.showElectricalTypes')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Pin Electrical Types')
      .Tooltip('Annotate pins with their electrical types')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.pin_show_etype),
  );

  static readonly showPinNumbers = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.showPinNumbers')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Pin Numbers')
      .Tooltip('Annotate pins with their numbers')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.pin),
  );

  static readonly exportSymbolView = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.exportSymbolView')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export View as PNG...')
      .Tooltip('Create PNG file from the current view')
      .Icon(BITMAPS.export_png),
  );

  static readonly exportSymbolAsSVG = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.exportSymbolAsSVG')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Symbol as SVG...')
      .Tooltip('Create SVG file from the current symbol')
      .Icon(BITMAPS.export_svg),
  );

  static readonly toggleSyncedPinsMode = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.toggleSyncedPinsMode')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Synchronized Pins Mode')
      .Tooltip(
        'Synchronized Pins Mode\nWhen enabled propagates all changes (except pin numbers) to other units.\nEnabled by default for multiunit parts with interchangeable units.',
      )
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.pin2pin),
  );

  static readonly showHiddenPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.showHiddenPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Hidden Pins')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.hidden_pin),
  );

  static readonly showHiddenFields = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.showHiddenFields')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Hidden Fields')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.text_sketch),
  );

  static readonly previousSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.previousSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Display previous symbol')
      .Icon(BITMAPS.lib_previous),
  );

  static readonly nextSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolLibraryControl.nextSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Display next symbol')
      .Icon(BITMAPS.lib_next),
  );

  static readonly placeSymbolPin = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolDrawing.placeSymbolPin')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('P'))
      .LegacyHotkeyName('Create Pin')
      .FriendlyName('Draw Pins')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.pin)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(KICAD_T.SCH_PIN_T),
  );

  static readonly placeSymbolText = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolDrawing.placeSymbolText')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Text')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.text)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(KICAD_T.SCH_TEXT_T),
  );

  static readonly drawSymbolTextBox = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolDrawing.drawSymbolTextBox')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Text Boxes')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_textbox)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly drawSymbolLines = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolDrawing.drawSymbolLines')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Lines')
      .Tooltip('Draw connected graphic lines')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_graphical_segments)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.POLY),
  );

  static readonly drawSymbolPolygon = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolDrawing.drawSymbolPolygon')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Polygons')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_graphical_polygon)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.POLY),
  );

  static readonly placeSymbolAnchor = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.SymbolDrawing.placeSymbolAnchor')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Move Symbol Anchor')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.anchor)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly pushPinLength = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.PinEditing.pushPinLength')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Push Pin Length')
      .Tooltip('Copy pin length to other pins in symbol')
      .Icon(BITMAPS.pin_size_to),
  );

  static readonly pushPinNameSize = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.PinEditing.pushPinNameSize')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Push Pin Name Size')
      .Tooltip('Copy pin name size to other pins in symbol')
      .Icon(BITMAPS.pin_size_to),
  );

  static readonly pushPinNumSize = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.PinEditing.pushPinNumSize')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Push Pin Number Size')
      .Tooltip('Copy pin number size to other pins in symbol')
      .Icon(BITMAPS.pin_size_to),
  );

  static readonly placeSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('A'))
      .LegacyHotkeyName('Add Symbol')
      .FriendlyName('Place Symbols')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_component)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<PLACE_SYMBOL_PARAMS>({ m_Symbol: null, m_Reannotate: true }),
  );

  static readonly placeNextSymbolUnit = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeNextSymbolUnit')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Place Next Symbol Unit')
      .Tooltip('Place the next unit of the current symbol that is missing from the schematic')
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<PLACE_SYMBOL_UNIT_PARAMS>({ m_Symbol: null, m_Unit: 0 }),
  );

  static readonly placePower = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placePowerSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('P'))
      .LegacyHotkeyName('Add Power')
      .FriendlyName('Place Power Symbols')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_power)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<PLACE_SYMBOL_PARAMS>({ m_Symbol: null, m_Reannotate: true }),
  );

  static readonly placeDesignBlock = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeDesignBlock')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_SHIFT + ch('B'))
      .FriendlyName('Place Design Block')
      .Tooltip('Add selected design block to current sheet')
      .Icon(BITMAPS.add_component)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<DESIGN_BLOCK | null>(null),
  );

  static readonly placeLinkedDesignBlock = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeLinkedDesignBlock')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Place Linked Design Block')
      .Tooltip('Place design block linked to selected group')
      .Icon(BITMAPS.add_component)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly saveToLinkedDesignBlock = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.saveToLinkedDesignBlock')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Save to Linked Design Block')
      .Tooltip('Save selected group to linked design block')
      .Icon(BITMAPS.add_component)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly placeNoConnect = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeNoConnect')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('Q'))
      .LegacyHotkeyName('Add No Connect Flag')
      .FriendlyName('Place No Connect Flags')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.noconn)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(KICAD_T.SCH_NO_CONNECT_T),
  );

  static readonly placeJunction = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeJunction')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('J'))
      .LegacyHotkeyName('Add Junction')
      .FriendlyName('Place Junctions')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_junction)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(KICAD_T.SCH_JUNCTION_T),
  );

  static readonly placeBusWireEntry = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeBusWireEntry')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('Z'))
      .LegacyHotkeyName('Add Wire Entry')
      .FriendlyName('Place Wire to Bus Entries')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_line2bus)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(KICAD_T.SCH_BUS_WIRE_ENTRY_T),
  );

  static readonly placeLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('L'))
      .LegacyHotkeyName('Add Label')
      .FriendlyName('Place Net Labels')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_label)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly placeClassLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeClassLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Place Directive Labels')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_class_flag)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly placeHierLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeHierarchicalLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('H'))
      .LegacyHotkeyName('Add Hierarchical Label')
      .FriendlyName('Place Hierarchical Labels')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_hierarchical_label)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly drawSheet = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawSheet')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('S'))
      .LegacyHotkeyName('Add Sheet')
      .FriendlyName('Draw Hierarchical Sheets')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_hierarchical_subsheet)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(KICAD_T.SCH_SHEET_T),
  );

  static readonly drawSheetFromFile = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawSheetFromFile')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Sheet from File')
      .Tooltip('Copy sheet into project and draw on current sheet')
      .Icon(BITMAPS.add_hierarchical_subsheet)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<string | null>(null),
  );

  static readonly drawSheetFromDesignBlock = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawSheetFromDesignBlock')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Sheet from Design Block')
      .Tooltip('Copy design block into project as a sheet on current sheet')
      .Icon(BITMAPS.add_hierarchical_subsheet)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<DESIGN_BLOCK | null>(null),
  );

  static readonly placeSheetPin = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeSheetPin')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Place Pins from Sheet')
      .Tooltip('Add sheet pins from existing hierarchical labels found on that sheet')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_hierar_pin)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly autoplaceAllSheetPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.autoplaceAllSheetPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Autoplace All Sheet Pins')
      .Tooltip('Imports and auto places all sheet pins'),
  );

  static readonly syncSheetPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.syncSheetPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Sync Selected Sheet Pins...')
      .Tooltip('Synchronize selected sheet pins and hierarchical labels')
      .Icon(BITMAPS.import_hierarchical_label)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly syncAllSheetsPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.syncAllSheetsPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Sync All Sheet Pins...')
      .Tooltip('Synchronize all sheet pins and hierarchical labels')
      .Icon(BITMAPS.import_hierarchical_label)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly importSheet = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.importSheet')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Import Sheet...')
      .Tooltip('Import sheet into project')
      .Icon(BITMAPS.add_hierarchical_subsheet)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<string | null>(null),
  );

  static readonly placeGlobalLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeGlobalLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('L'))
      .LegacyHotkeyName('Add Global Label')
      .FriendlyName('Place Global Labels')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_glabel)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly placeSchematicText = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeSchematicText')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('T'))
      .LegacyHotkeyName('Add Graphic Text')
      .FriendlyName('Draw Text')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.text)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly drawTextBox = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawTextBox')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Text Boxes')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_textbox)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.RECTANGLE),
  );

  static readonly drawTable = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawTable')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Tables')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.table)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly drawRectangle = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawRectangle')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Rectangles')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_rectangle)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.RECTANGLE),
  );

  static readonly drawCircle = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawCircle')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Circles')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_circle)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.CIRCLE),
  );

  static readonly drawArc = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawArc')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Arcs')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_arc)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.ARC),
  );

  static readonly drawBezier = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawBezier')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Bezier Curve')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_bezier)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.BEZIER),
  );

  static readonly placeImage = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.placeImage')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Place Images')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.image)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<SCH_BITMAP | null>(null),
  );

  static readonly drawRuleArea = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.drawRuleArea')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Draw Rule Areas')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_keepout_area)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter(SHAPE_T.RECTANGLE),
  );

  static readonly deleteLastPoint = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.deleteLastPoint')
      .Scope(TOOL_ACTION_SCOPE.AS_CONTEXT)
      .FriendlyName('Delete Last Point')
      .Tooltip('Delete the last point added to the current item')
      .Icon(BITMAPS.undo),
  );

  static readonly closeOutline = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawing.closeOutline')
      .Scope(TOOL_ACTION_SCOPE.AS_CONTEXT)
      .FriendlyName('Close Outline')
      .Tooltip('Close the in-progress outline')
      .Icon(BITMAPS.checked_ok),
  );

  static readonly repeatDrawItem = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.repeatDrawItem')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(WXK.WXK_F1)
      .DefaultHotkey(WXK.WXK_INSERT)
      .LegacyHotkeyName('Repeat Last Item')
      .FriendlyName('Repeat Last Item')
      .Tooltip('Duplicates the last drawn item'),
  );

  static readonly rotateCW = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.rotateCW')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_SHIFT + ch('R'))
      .FriendlyName('Rotate Clockwise')
      .Icon(BITMAPS.rotate_cw),
  );

  static readonly rotateCCW = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.rotateCCW')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('R'))
      .LegacyHotkeyName('Rotate Item')
      .FriendlyName('Rotate Counterclockwise')
      .Icon(BITMAPS.rotate_ccw),
  );

  static readonly mirrorV = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.mirrorV')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('Y'))
      .LegacyHotkeyName('Mirror X')
      .FriendlyName('Mirror Vertically')
      .Tooltip('Flips selected item(s) from top to bottom')
      .Icon(BITMAPS.mirror_v),
  );

  static readonly mirrorH = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.mirrorH')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('X'))
      .LegacyHotkeyName('Mirror Y')
      .FriendlyName('Mirror Horizontally')
      .Tooltip('Flips selected item(s) from left to right')
      .Icon(BITMAPS.mirror_h),
  );

  static readonly swap = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.swap')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_ALT + ch('S'))
      .FriendlyName('Swap')
      .Tooltip('Swap positions of selected items')
      .Icon(BITMAPS.swap),
  );

  static readonly swapPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.swapPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Swap Pins')
      .Tooltip("Swap the selected symbol pins' positions")
      .Icon(BITMAPS.swap),
  );

  static readonly swapPinLabels = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.swapPinLabels')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Swap Pin Labels')
      .Tooltip('Swap the labels attached to selected pins')
      .Icon(BITMAPS.swap),
  );

  static readonly swapUnitLabels = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.swapUnitLabels')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Swap Unit Labels')
      .Tooltip('Swap labels between selected units')
      .Icon(BITMAPS.swap),
  );

  static readonly properties = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.properties')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('E'))
      .LegacyHotkeyName('Edit Item')
      .FriendlyName('Properties...')
      .Icon(BITMAPS.edit),
  );

  static readonly editReference = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.editReference')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('U'))
      .LegacyHotkeyName('Edit Symbol Reference')
      .FriendlyName('Edit Reference Designator...')
      .Icon(BITMAPS.edit_comp_ref),
  );

  static readonly editValue = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.editValue')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('V'))
      .LegacyHotkeyName('Edit Symbol Value')
      .FriendlyName('Edit Value...')
      .Icon(BITMAPS.edit_comp_value),
  );

  static readonly editFootprint = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.editFootprint')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('F'))
      .LegacyHotkeyName('Edit Symbol Footprint')
      .FriendlyName('Edit Footprint...')
      .Icon(BITMAPS.edit_comp_footprint),
  );

  static readonly autoplaceFields = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.autoplaceFields')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('O'))
      .LegacyHotkeyName('Autoplace Fields')
      .FriendlyName('Autoplace Fields')
      .Tooltip("Runs the automatic placement algorithm on the symbol's (or sheet's) fields")
      .Icon(BITMAPS.autoplace_fields),
  );

  static readonly changeSymbols = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.changeSymbols')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change Symbols...')
      .Tooltip('Assign different symbols from the library')
      .Icon(BITMAPS.exchange),
  );

  static readonly updateSymbols = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.updateSymbols')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Update Symbols from Library...')
      .Tooltip('Update symbols to include any changes from the library')
      .Icon(BITMAPS.refresh),
  );

  static readonly changeSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.changeSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change Symbol...')
      .Tooltip('Assign a different symbol from the library')
      .Icon(BITMAPS.exchange),
  );

  static readonly updateSymbol = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.updateSymbol')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Update Symbol...')
      .Tooltip('Update symbol to include any changes from the library')
      .Icon(BITMAPS.refresh),
  );

  static readonly assignNetclass = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.assignNetclass')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Assign Netclass...')
      .Tooltip('Assign a netclass to nets matching a pattern')
      .Icon(BITMAPS.netlist),
  );

  static readonly findNetInInspector = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.findNetInInspector')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Find in Net Navigator')
      .Tooltip('Locate the selected net in the net navigator'),
  );

  static readonly cycleBodyStyle = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.toggleDeMorgan')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Cycle Body Style')
      .Tooltip('Switch between De Morgan (or other) representations')
      .Icon(BITMAPS.morgan2),
  );

  static readonly toLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.toLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change to Label')
      .Tooltip('Change existing item to a label')
      .Icon(BITMAPS.add_line_label)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(KICAD_T.SCH_LABEL_T),
  );

  static readonly toDLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.toCLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change to Directive Label')
      .Tooltip('Change existing item to a directive label')
      .Icon(BITMAPS.add_class_flag)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(KICAD_T.SCH_DIRECTIVE_LABEL_T),
  );

  static readonly toHLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.toHLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change to Hierarchical Label')
      .Tooltip('Change existing item to a hierarchical label')
      .Icon(BITMAPS.add_hierarchical_label)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(KICAD_T.SCH_HIER_LABEL_T),
  );

  static readonly toGLabel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.toGLabel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change to Global Label')
      .Tooltip('Change existing item to a global label')
      .Icon(BITMAPS.add_glabel)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(KICAD_T.SCH_GLOBAL_LABEL_T),
  );

  static readonly toText = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.toText')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change to Text')
      .Tooltip('Change existing item to a text comment')
      .Icon(BITMAPS.text)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(KICAD_T.SCH_TEXT_T),
  );

  static readonly toTextBox = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.toTextBox')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Change to Text Box')
      .Tooltip('Change existing item to a text box')
      .Icon(BITMAPS.add_textbox)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(KICAD_T.SCH_TEXTBOX_T),
  );

  static readonly cleanupSheetPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.cleanupSheetPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Cleanup Sheet Pins')
      .Tooltip('Delete unreferenced sheet pins'),
  );

  static readonly editTextAndGraphics = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.editTextAndGraphics')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Edit Text & Graphics Properties...')
      .Tooltip('Edit text and graphics properties globally across schematic')
      .Icon(BITMAPS.text),
  );

  static readonly symbolProperties = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.symbolProperties')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Symbol Properties...')
      .Icon(BITMAPS.part_properties),
  );

  static readonly pinTable = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.pinTable')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Pin Table...')
      .Tooltip('Displays pin table for bulk editing of pins')
      .Icon(BITMAPS.pin_table),
  );

  static readonly convertStackedPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.convertStackedPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Convert Stacked Pins')
      .Tooltip('Convert multiple pins at the same location to a single pin with stacked notation')
      .Icon(BITMAPS.pin),
  );

  static readonly explodeStackedPin = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.explodeStackedPin')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Explode Stacked Pin')
      .Tooltip('Convert a pin with stacked notation to multiple individual pins')
      .Icon(BITMAPS.pin),
  );

  static readonly breakWire = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.breakWire')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Break')
      .Tooltip('Divide into connected segments')
      .Icon(BITMAPS.break_line),
  );

  static readonly slice = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveEdit.slice')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Slice')
      .Tooltip('Divide into unconnected segments')
      .Icon(BITMAPS.slice_line),
  );

  static readonly restartMove = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.restartMove')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL),
  );

  static readonly highlightNet = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.highlightNet')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('`'))
      .FriendlyName('Highlight Net')
      .Tooltip('Highlight net under cursor')
      .Icon(BITMAPS.net_highlight_schematic),
  );

  static readonly clearHighlight = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.clearHighlight')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('~'))
      .FriendlyName('Clear Net Highlighting')
      .Tooltip('Clear any existing net highlighting'),
  );

  static readonly updateNetHighlighting = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.updateNetHighlighting')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL),
  );

  static readonly highlightNetTool = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.highlightNetTool')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Highlight Nets')
      .Tooltip('Highlight wires and pins of a net')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.net_highlight_schematic)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly showNetNavigator = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showNetNavigator')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Net Navigator')
      .Tooltip('Show/hide the net navigator'),
  );

  static readonly editWithLibEdit = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.editWithSymbolEditor')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('E'))
      .LegacyHotkeyName('Edit with Symbol Editor')
      .FriendlyName('Edit with Symbol Editor')
      .Tooltip('Open the selected symbol in the Symbol Editor')
      .Icon(BITMAPS.libedit),
  );

  static readonly setExcludeFromBOM = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.setExcludeFromBOM')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Exclude from Bill of Materials')
      .Tooltip('Set the exclude from bill of materials attribute'),
  );

  static readonly setExcludeFromSim = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.setExcludeFromSimulation')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Exclude from Simulation')
      .Tooltip('Set the exclude from simulation attribute'),
  );

  static readonly setExcludeFromBoard = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.setExcludeFromBoard')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Exclude from Board')
      .Tooltip('Set the exclude from board attribute'),
  );

  static readonly setExcludeFromPosFiles = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.setExcludeFromPosFiles')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Exclude from Position Files')
      .Tooltip('Set the exclude from position files attribute'),
  );

  static readonly setDNP = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.setDNP')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Do not Populate')
      .Tooltip('Set the do not populate attribute'),
  );

  static readonly editLibSymbolWithLibEdit = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.editLibSymbolWithSymbolEditor')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + MD_SHIFT + ch('E'))
      .FriendlyName('Edit Library Symbol...')
      .Tooltip('Open the library symbol in the Symbol Editor')
      .Icon(BITMAPS.libedit),
  );

  static readonly editSymbolFields = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.editSymbolFields')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Bulk Edit Symbol Fields...')
      .Tooltip('Edit a table of fields from all symbols in the schematic')
      .Icon(BITMAPS.spreadsheet),
  );

  static readonly editSymbolLibraryLinks = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.editSymbolLibraryLinks')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Bulk Edit Symbol Library Links...')
      .Tooltip('Edit a table of links between schematic and library symbols')
      .Icon(BITMAPS.edit_cmp_symb_links),
  );

  static readonly assignFootprints = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.assignFootprints')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Assign Footprints...')
      .Tooltip('Run footprint assignment tool')
      .Icon(BITMAPS.icon_cvpcb_24),
  );

  static readonly importFPAssignments = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.importFPAssignments')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Import Footprint Assignments...')
      .Tooltip('Import symbol footprint assignments from .cmp file created by board editor')
      .Icon(BITMAPS.import_footprint_names),
  );

  static readonly annotate = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.annotate')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Annotate Schematic...')
      .Tooltip('Fill in schematic symbol reference designators')
      .Icon(BITMAPS.annotate),
  );

  static readonly incrementAnnotations = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.incrementAnnotations')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Increment Annotations From...')
      .Tooltip('Increment a subset of reference designators starting at a particular symbol')
      .Icon(BITMAPS.annotate_increment),
  );

  static readonly schematicSetup = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.schematicSetup')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Schematic Setup...')
      .Tooltip('Edit schematic setup including annotation styles and electrical rules')
      .Icon(BITMAPS.options_schematic),
  );

  static readonly editPageNumber = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.editPageNumber')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Edit Sheet Page Number...')
      .Tooltip('Edit the page number of the current or selected sheet'),
  );

  static readonly rescueSymbols = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.rescueSymbols')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Rescue Symbols...')
      .Tooltip('Find old symbols in project and rename/rescue them')
      .Icon(BITMAPS.rescue),
  );

  static readonly remapSymbols = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.remapSymbols')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Remap Legacy Library Symbols...')
      .Tooltip('Remap library symbol references in legacy schematics to the symbol library table')
      .Icon(BITMAPS.rescue),
  );

  static readonly nextNetItem = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.nextNetItem')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(WXK.WXK_TAB)
      .FriendlyName('Next Net Item')
      .Tooltip('Select next item on the current net'),
  );

  static readonly previousNetItem = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.previousNetItem')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_SHIFT + WXK.WXK_TAB)
      .FriendlyName('Previous Net Item')
      .Tooltip('Select previous item on the current net'),
  );

  static readonly drawSheetOnClipboard = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.drawSheetOnClipboard')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Drawing to Clipboard')
      .Tooltip('Export drawing of current sheet to clipboard')
      .Icon(BITMAPS.copy),
  );

  static readonly importGraphics = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.importGraphics')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + MD_SHIFT + ch('F'))
      .LegacyHotkeyName('Place DXF')
      .FriendlyName('Import Graphics...')
      .Tooltip('Import 2D drawing file')
      .Icon(BITMAPS.import_vector)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly importNonKicadSchematic = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.importNonKicadSchematic')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Import Non-KiCad Schematic...')
      .Tooltip('Replace current schematic sheet with one imported from another application')
      .Icon(BITMAPS.import_document),
  );

  static readonly showPcbNew = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showPcbNew')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Switch to PCB Editor')
      .Tooltip('Open PCB in board editor')
      .Icon(BITMAPS.icon_pcbnew_24),
  );

  static readonly exportNetlist = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.exportNetlist')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Netlist...')
      .Tooltip('Export file containing netlist in one of several formats')
      .Icon(BITMAPS.netlist),
  );

  static readonly generateBOM = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.generateBOM')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Generate Bill of Materials...')
      .Tooltip('Generate a bill of materials for the current schematic')
      .Icon(BITMAPS.post_bom),
  );

  static readonly generateBOMLegacy = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.generateBOMLegacy')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Generate Legacy Bill of Materials...')
      .Tooltip('Generate a bill of materials for the current schematic (Legacy Generator)')
      .Icon(BITMAPS.file_bom),
  );

  static readonly generateBOMExternal = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.generateBOMExternal')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Generate Bill of Materials (External)...')
      .Tooltip('Generate a bill of materials for the current schematic using external generator'),
  );

  static readonly exportSymbolsToLibrary = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.exportSymbolsToLibrary')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Symbols...')
      .Tooltip(
        'Add symbols from schematic to a new or an existing symbol library\n(does not remove other symbols from this library)',
      )
      .Icon(BITMAPS.library_archive),
  );

  static readonly selectOnPCB = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.selectOnPCB')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Select on PCB')
      .Tooltip('Select corresponding items in PCB editor')
      .Icon(BITMAPS.select_same_sheet),
  );

  static readonly toggleHiddenPins = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showHiddenPins')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Hidden Pins')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.hidden_pin),
  );

  static readonly toggleHiddenFields = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showHiddenFields')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Hidden Fields')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly toggleDirectiveLabels = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showDirectiveLabels')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Directive Labels')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly toggleERCWarnings = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showERCWarnings')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show ERC Warnings')
      .Tooltip('Show markers for electrical rules checker warnings')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly toggleERCErrors = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showERCErrors')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show ERC Errors')
      .Tooltip('Show markers for electrical rules checker errors')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly toggleERCExclusions = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showERCExclusions')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show ERC Exclusions')
      .Tooltip('Show markers for excluded electrical rules checker violations')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly markSimExclusions = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.markSimExclusions')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Mark items excluded from simulation')
      .Tooltip("Draw 'X's over items which have been excluded from simulation")
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly toggleOPVoltages = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showOperatingPointVoltages')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show OP Voltages')
      .Tooltip('Show operating point voltage data from simulation')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly toggleOPCurrents = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.showOperatingPointCurrents')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show OP Currents')
      .Tooltip('Show operating point current data from simulation')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly togglePinAltIcons = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.togglePinAltIcons')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Pin Alternate Icons')
      .Tooltip('Show indicator icons for pins with alternate modes')
      .ToolbarState(TOOLBAR_STATE.TOGGLE),
  );

  static readonly lineModeFree = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.lineModeFree')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Line Mode for Wires and Buses')
      .Tooltip('Draw and drag at any angle')
      .Icon(BITMAPS.lines_any)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(LINE_MODE.LINE_MODE_FREE),
  );

  static readonly lineMode90 = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.lineModeOrthonal')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Line Mode for Wires and Buses')
      .Tooltip('Constrain drawing and dragging to horizontal or vertical motions')
      .Icon(BITMAPS.lines90)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(LINE_MODE.LINE_MODE_90),
  );

  static readonly lineMode45 = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.lineMode45')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Line Mode for Wires and Buses')
      .Tooltip('Constrain drawing and dragging to horizontal, vertical, or 45-degree angle motions')
      .Icon(BITMAPS.hv45mode)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE)
      .Parameter(LINE_MODE.LINE_MODE_45),
  );

  static readonly lineModeNext = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.lineModeNext')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_SHIFT + WXK.WXK_SPACE)
      .FriendlyName('Line Mode for Wires and Buses')
      .Tooltip('Switch to next angle snapping mode'),
  );

  static readonly angleSnapModeChanged = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.angleSnapModeChanged')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .Flags(TOOL_ACTION_FLAGS.AF_NOTIFY),
  );

  static readonly toggleAnnotateAuto = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.annotateAutomatically')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Annotate Automatically')
      .Tooltip('Toggle automatic annotation of new symbols')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.annotate),
  );

  static readonly previousUnit = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.previousUnit')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Previous Symbol Unit')
      .Tooltip('Open the previous unit of the symbol')
      .Parameter(-1),
  );

  static readonly nextUnit = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.nextUnit')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Next Symbol Unit')
      .Tooltip('Open the next unit of the symbol')
      .Parameter(1),
  );

  static readonly changeSheet = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.changeSheet')
      .Scope(TOOL_ACTION_SCOPE.AS_CONTEXT)
      .FriendlyName('Change Sheet')
      .Tooltip("Change to provided sheet's contents in the schematic editor")
      .Icon(BITMAPS.enter_sheet),
  );

  static readonly enterSheet = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.enterSheet')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Enter Sheet')
      .Tooltip("Display the selected sheet's contents in the schematic editor")
      .Icon(BITMAPS.enter_sheet),
  );

  static readonly leaveSheet = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.leaveSheet')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_ALT + WXK.WXK_BACK)
      .LegacyHotkeyName('Leave Sheet')
      .FriendlyName('Leave Sheet')
      .Tooltip('Display the parent sheet in the schematic editor')
      .Icon(BITMAPS.leave_sheet),
  );

  static readonly navigateUp = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.up')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_ALT + WXK.WXK_UP)
      .FriendlyName('Navigate Up')
      .Tooltip('Navigate up one sheet in the hierarchy')
      .Icon(BITMAPS.up),
  );

  static readonly navigateBack = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.back')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_ALT + WXK.WXK_LEFT)
      .FriendlyName('Navigate Back')
      .Tooltip('Move backward in sheet navigation history')
      .Icon(BITMAPS.left),
  );

  static readonly navigateForward = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.forward')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_ALT + WXK.WXK_RIGHT)
      .FriendlyName('Navigate Forward')
      .Tooltip('Move forward in sheet navigation history')
      .Icon(BITMAPS.right),
  );

  static readonly navigatePrevious = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.previous')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(WXK.WXK_PAGEUP)
      .FriendlyName('Previous Sheet')
      .Tooltip('Move to previous sheet by number')
      .Icon(BITMAPS.left),
  );

  static readonly navigateNext = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.NavigateTool.next')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(WXK.WXK_PAGEDOWN)
      .FriendlyName('Next Sheet')
      .Tooltip('Move to next sheet by number')
      .Icon(BITMAPS.right),
  );

  static readonly showHierarchy = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorTool.showHierarchy')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('H'))
      .FriendlyName('Hierarchy Navigator')
      .Tooltip('Show/hide the schematic sheet hierarchy navigator')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.hierarchy_nav),
  );

  static readonly drawWire = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawingLineWireBus.drawWires')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('W'))
      .LegacyHotkeyName('Begin Wire')
      .FriendlyName('Draw Wires')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_line)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter({ layer: SCH_LAYER_ID.LAYER_WIRE, quitOnDraw: false, sourceSegment: null }),
  );

  static readonly drawBus = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawingLineWireBus.drawBuses')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('B'))
      .LegacyHotkeyName('Begin Bus')
      .FriendlyName('Draw Buses')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_bus)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter({ layer: SCH_LAYER_ID.LAYER_BUS, quitOnDraw: false, sourceSegment: null }),
  );

  static readonly unfoldBus = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawingLineWireBus.unfoldBus')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('C'))
      .LegacyHotkeyName('Unfold from Bus')
      .FriendlyName('Unfold from Bus')
      .Tooltip('Break a wire out of a bus')
      .Icon(BITMAPS.INVALID_BITMAP)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter<string | null>(null),
  );

  static readonly drawLines = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawingLineWireBus.drawLines')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('I'))
      .LegacyHotkeyName('Add Graphic PolyLine')
      .FriendlyName('Draw Lines')
      .ToolbarState(TOOLBAR_STATE.TOGGLE)
      .Icon(BITMAPS.add_graphical_segments)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE)
      .Parameter({ layer: SCH_LAYER_ID.LAYER_NOTES, quitOnDraw: false, sourceSegment: null }),
  );

  static readonly undoLastSegment = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawingLineWireBus.undoLastSegment')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(WXK.WXK_BACK)
      .FriendlyName('Undo Last Segment')
      .Tooltip('Walks the current line back one segment.')
      .Icon(BITMAPS.undo),
  );

  static readonly switchSegmentPosture = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveDrawingLineWireBus.switchPosture')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('/'))
      .FriendlyName('Switch Segment Posture')
      .Tooltip('Switches posture of the current segment.')
      .Icon(BITMAPS.change_entry_orient)
      .Flags(TOOL_ACTION_FLAGS.AF_NONE),
  );

  static readonly move = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveMove.move')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('M'))
      .LegacyHotkeyName('Move Item')
      .FriendlyName('Move')
      .Icon(BITMAPS.move)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly drag = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.InteractiveMove.drag')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('G'))
      .LegacyHotkeyName('Drag Item')
      .FriendlyName('Drag')
      .Tooltip('Move items while keeping their connections')
      .Icon(BITMAPS.drag)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly alignToGrid = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.AlignToGrid')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Align Items to Grid')
      .Icon(BITMAPS.align_elements_to_grid)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly alignTop = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Align.alignTop')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Align to Top')
      .Tooltip('Aligns selected items to the top edge of the item under the cursor')
      .Icon(BITMAPS.align_items_top)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly alignBottom = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Align.alignBottom')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Align to Bottom')
      .Tooltip('Aligns selected items to the bottom edge of the item under the cursor')
      .Icon(BITMAPS.align_items_bottom)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly alignLeft = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Align.alignLeft')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Align to Left')
      .Tooltip('Aligns selected items to the left edge of the item under the cursor')
      .Icon(BITMAPS.align_items_left)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly alignRight = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Align.alignRight')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Align to Right')
      .Tooltip('Aligns selected items to the right edge of the item under the cursor')
      .Icon(BITMAPS.align_items_right)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly alignCenterX = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Align.alignCenterX')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Align to Horizontal Center')
      .Tooltip('Aligns selected items to the horizontal center of the item under the cursor')
      .Icon(BITMAPS.align_items_middle)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly alignCenterY = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Align.alignCenterY')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Align to Vertical Center')
      .Tooltip('Aligns selected items to the vertical center of the item under the cursor')
      .Icon(BITMAPS.align_items_center)
      .Flags(TOOL_ACTION_FLAGS.AF_ACTIVATE),
  );

  static readonly saveCurrSheetCopyAs = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.saveCurrSheetCopyAs')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Save Current Sheet Copy As...')
      .Tooltip('Save a copy of the current sheet to another location or name')
      .Icon(BITMAPS.save_as),
  );

  static readonly ddAppendFile = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.ddAppendFile')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL),
  );

  static readonly ddAddImage = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.ddAddImage')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL),
  );

  static readonly ddImportGraphics = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.ddImportGraphics')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL),
  );

  static readonly newAnalysisTab = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.newAnalysisTab')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('N'))
      .LegacyHotkeyName('New')
      .FriendlyName('New Analysis Tab...')
      .Tooltip('Create a new tab containing a simulation analysis')
      .Icon(BITMAPS.sim_add_plot),
  );

  static readonly openWorkbook = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.openWorkbook')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('O'))
      .LegacyHotkeyName('Open')
      .FriendlyName('Open Workbook...')
      .Tooltip('Open a saved set of analysis tabs and settings')
      .Icon(BITMAPS.directory_open),
  );

  static readonly saveWorkbook = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.saveWorkbook')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + ch('S'))
      .LegacyHotkeyName('Save')
      .FriendlyName('Save Workbook')
      .Tooltip('Save the current set of analysis tabs and settings')
      .Icon(BITMAPS.save),
  );

  static readonly saveWorkbookAs = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.saveWorkbookAs')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_CTRL + MD_SHIFT + ch('S'))
      .LegacyHotkeyName('Save As')
      .FriendlyName('Save Workbook As...')
      .Tooltip('Save the current set of analysis tabs and settings to another location')
      .Icon(BITMAPS.sim_add_signal),
  );

  static readonly exportPlotAsPNG = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.exportPNG')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Current Plot as PNG...')
      .Icon(BITMAPS.export_png),
  );

  static readonly exportPlotAsCSV = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.exportCSV')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Current Plot as CSV...')
      .Icon(BITMAPS.export_file),
  );

  static readonly exportPlotToClipboard = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.exportToClipboard')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Current Plot to Clipboard')
      .Icon(BITMAPS.export_png),
  );

  static readonly exportPlotToSchematic = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.exportPlotToSchematic')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Export Current Plot to Schematic')
      .Icon(BITMAPS.export_png),
  );

  static readonly toggleSimSidePanel = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.toggleSimSidePanel')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Simulation Side Panel'),
  );

  static readonly toggleSimConsole = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.toggleSimConsole')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Simulation Console Panel'),
  );

  static readonly toggleLegend = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.toggleLegend')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show Legend')
      .Icon(BITMAPS.text),
  );

  static readonly toggleDottedSecondary = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.toggleDottedSecondary')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Dotted Current/Phase')
      .Tooltip('Draw secondary signal trace (current or phase) with a dotted line'),
  );

  static readonly toggleDarkModePlots = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulator.toggleDarkModePlots')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Dark Mode Plots')
      .Tooltip('Draw plots with a black background'),
  );

  static readonly simAnalysisProperties = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.simAnalysisProperties')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Edit Analysis Tab...')
      .Tooltip("Edit the current analysis tab's SPICE command and plot setup")
      .Icon(BITMAPS.sim_command),
  );

  static readonly runSimulation = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.runSimulation')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(ch('R'))
      .FriendlyName('Run Simulation')
      .Icon(BITMAPS.sim_run),
  );

  static readonly stopSimulation = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.stopSimulation')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Stop Simulation')
      .Icon(BITMAPS.sim_stop),
  );

  static readonly simProbe = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.probe')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_SHIFT + ch('P'))
      .FriendlyName('Probe Schematic...')
      .Tooltip('Add a simulator probe')
      .Icon(BITMAPS.sim_probe),
  );

  static readonly simTune = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.tune')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .DefaultHotkey(MD_SHIFT + ch('T'))
      .FriendlyName('Add Tuned Value...')
      .Tooltip('Select a value to be tuned')
      .Icon(BITMAPS.sim_tune),
  );

  static readonly editUserDefinedSignals = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.editUserDefinedSignals')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('User-defined Signals...')
      .Tooltip('Add, edit or delete user-defined simulation signals')
      .Icon(BITMAPS.sim_add_signal),
  );

  static readonly showNetlist = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.Simulation.showNetlist')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Show SPICE Netlist')
      .Icon(BITMAPS.netlist),
  );

  static readonly addVariant = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.addVariant')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Add Design Variant...')
      .Tooltip('Add new design variant to the schematic.'),
  );

  static readonly removeVariant = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.removeVariant')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Remove Design Variant...')
      .Tooltip('Remove an existing design variant from the schematic.'),
  );

  static readonly editVariantDescription = new TOOL_ACTION(
    new TOOL_ACTION_ARGS()
      .Name('eeschema.EditorControl.editVariantDescription')
      .Scope(TOOL_ACTION_SCOPE.AS_GLOBAL)
      .FriendlyName('Edit Variant Description...')
      .Tooltip('Edit the description of an existing design variant.'),
  );
}
